### ISSUE TITLE
Created PDF's path cannot be found by RN-fetch-blob on Android

### ISSUE THREAD

**Issue by jefferyFarlyProvencher** [christopherdro/react-native-html-to-pdf#100]
Hello, 

As the title suggest, it seems that the package react-native fetch-blob cannot find, on android, the path given by file.filePath when trying to open it. As for IOS, on the emulator at least, it works as expected.

So I was wondering if it is possible that the path that is returned by file.filePath could not actually be the right path afterall...

Or is it maybe something to do with the name of the pdf file itself, as it returns a path towards a file with the name PDF_random-Series-Of-Numbers instead of the FileName that was set to it.

Here is an image of the error I get when trying to open the pdf:
![error_not_found_android](https://user-images.githubusercontent.com/17105333/51407321-8a55d200-1b29-11e9-8f35-48565c80851e.jpg)

And here is a snippet of my code:

generatePDF = () => {

        let html = this.generateHTML(currentResult);

        let fileName = currentResult.name;
        
        let options = {
            html: html,
            fileName: (fileName),
            directory: (Platform.OS === 'ios')? 'Documents': 'Downloads',
            base64: true
        };

        let file = await RNHTMLtoPDF.convert(options);

        //console.log("Base64: "+ file.base64)

    
        await alert(
            ("'PDF Creation Confirmation' The pdf was created at this location: " +file.filePath)
        );

        this.props.onAddPDFToResult(this.state.currentPosition, file.filePath);
}
               

openGeneratedPDF = () => {

        let path = currentResult.PDFPath;
        
        if(Platform.OS === "ios"){
            RNFetchBlob.ios.openDocument(path);
        }
        else{
            const android = RNFetchBlob.android;
            android.actionViewIntent(path, 'application/pdf');
        }
 }

Thank you

**Comment by odarino** [comment]
Same with me. I believe that file has been never created. Tried it by checking in File Explorer on Android. But file has been created successfully on iOS. 
- RN 0.58.5
- RNHTMLToPDF: 0.8.0
