### ISSUE TITLE
Module is undefined

### ISSUE THREAD

**Issue by AxelPariss** [christopherdro/react-native-html-to-pdf#103]
Hello everyone,

I have this issue : when I'm importing the module, it is undefined. 
`import RNHTMLtoPDF from 'react-native-html-to-pdf'`

When I pass my mouse on the inclusion, I got this information (from VSCode) : 
```
Could not find a declaration file for module 'react-native-html-to-pdf'. '/Users/axelparis/GoogleDrive/development/projects/swalloows/app/swalloows-app/node_modules/react-native-html-to-pdf/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-html-to-pdf` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-html-to-pdf';`ts(7016)
module "/Users/axelparis/GoogleDrive/development/projects/swalloows/app/swalloows-app/node_modules/react-native-html-to-pdf/index"
```

(I tried npm install @types/react-native-html-to-pdf but that didn't work)

How can I solve this problem ? Thanks :)

**Comment by Sivakumar00** [comment]
Did any one solved it?? If yes, kindly post the solution

**Comment by durac** [comment]
Add //@ts-ignore above the line. 
This is just a typescript warning, because this module doesn't provide types.

**Comment by jefferson-calmon** [comment]
Run 

`npm install @types/react-native-html-to-pdf`
or
`yarn add @types/react-native-html-to-pdf`

in your terminal.
