### ISSUE TITLE
Output pdf suddenly blank, before it works fine

### ISSUE THREAD

**Issue by agrapana** [christopherdro/react-native-html-to-pdf#106]
i'm making an app in react-native and using plugin react-native-html-to-pdf in it, and it worked like a charm.

a couple days ago, the pdf suddenly only showing a logo and some details at the above part, and the below part is blank,

i tried to find out what happen for several days already,

could someone point me out, what should i do, or what happened?

this is the image of pdf when it works normal =
![fine_1_xs](https://user-images.githubusercontent.com/47593112/52770880-e9dec900-3066-11e9-8f8a-537b0eb74ac7.jpg)

this is the image of current pdf =
![blank_1_xs](https://user-images.githubusercontent.com/47593112/52770885-ec412300-3066-11e9-9a9f-c131a93be024.jpg)

info =
"react-native": "0.55.4",
"react-native-html-to-pdf": "^0.6.0",

compileSdkVersion 25
buildToolsVersion "25.0.1"

> dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile project(':react-native-navigation')
    compile project(':react-native-image-picker')
    compile project(':react-native-contacts')
    compile project(':react-native-vector-icons')
    compile project(':react-native-html-to-pdf')
    compile project(':react-native-share')
}

> // Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

> buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://dl.google.com/dl/android/maven2/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

thank you

**Comment by aureliopetrone** [comment]
It's because the # character. Try change colors from hexcode to html string colors (#ffffff to 'white').

**Comment by Sanakhatun** [comment]
how to use function within html string in this library? I want to set dynamic values to html table ...
