### ISSUE TITLE
Please remove the example folder from your npm package

### ISSUE THREAD

**Issue by shubhang93** [christopherdro/react-native-html-to-pdf#107]
Please remove the example folder from your npm package it causes naming collisions with the existing react-native package, since react-native gets installed twice and the bundler  fails to transform. A temporary fix for all you people who are experiencing the same, please add this to your package.json 
```
{"postInstall":"rm -rf node_modules/react-native-html-to-pdf/example"}
```
Note: Please run npm start -- --reset-cache if you still see a naming collision error.

**Comment by psalmeight** [comment]
This was also my concern. I was wondering why there were naming collisions and had to remove it manually.

**Comment by desarrollospyro** [comment]
+1

**Comment by blueturtle13g** [comment]
@shubhang93 where should I add this line? ``` {"postInstall":"rm -rf node_modules/react-native-html-to-pdf/example"} ``` ?
I added it  to scripts:
```   
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "postInstall":"rm node_modules/react-native-html-to-pdf/example"
  }
```
but it doesn't work, and when I run ``` npm start -- --reset-cache ```! it throws the name collision error.
my OS is windows 10.
could you give me an example?

**Comment by GreenRidingHood** [comment]
i am just deleting manually :( all the time. @blueturtle13g did it work for you?
