### ISSUE TITLE
Add param to change the Background Color in iOS

### ISSUE THREAD

**Issue by sydg** [christopherdro/react-native-html-to-pdf#111]
First, thanks for this library, it's very helpful.

I need to change the background Color for iOS

![image](https://user-images.githubusercontent.com/5825846/53963190-29775e80-40c3-11e9-9bd7-930f46290dbd.png)

I search in the code and find in the file **ios/RNHTMLtoPDF/RNHTMLtoPDF.m**, the line 29:

`UIColor *myColor = [UIColor colorWithRed: (246.0/255.0) green:(245.0/255.0) blue:(240.0/255.0) alpha:1];`

In my case I need a white background.

What do you think in add a param to change the background color?

**Comment by sydg** [comment]
I did the change in [#112](https://github.com/christopherdro/react-native-html-to-pdf/pull/112)

**Comment by xsami** [comment]
Really good feature. Just what I wanted 👍

**Comment by nikitpanchal** [comment]
adding bgColor : '#FFFFF' not working

**Comment by dhruvjain1800** [comment]
Any update on this. I am facing the same issue. background-color is not working

**Comment by SodaisNasir** [comment]
I am also facing same issue background color not working in ios

**Comment by Ranvijay-DX** [comment]
i don't understand 

even without Solutions , how Issues are getting closed??

**Comment by RanvijayChouhan12** [comment]
```
import RNHTMLtoPDF from "react-native-html-to-pdf";

  let options = {
    html: htmlContent, // Your HTML Page
    fileName: "PDF_Name",
    directory: "Documents",
    padding: 0,
    bgColor: "#FFFFFF",
  };

  let file = await RNHTMLtoPDF.convert(options);
```

use  bgColor: "#FFFFFF", as 6 character Color Code it wors Fine for IOS, I haven't tested for Android Yet, 

Please Confirm if you have Tested on Android

Thank You, 
Happy Coading 👍🏻

**Comment by bumpingChris** [comment]
I tried using bgColor in iOS:

`let options = {
            html: '<html><head></head><body><h1>Yeah</h1></body></html>', 
            fileName: 'DLTest',
            directory: 'Documents',
            height: pdfHeightPoints, 
            width: pdfWidthPoints, 
            padding: 0, 
            bgColor: '#EE7887',
        };        
        let file = await RNHTMLtoPDF.convert(options);`

But it appears to be ignoring bgColor...
