### ISSUE TITLE
.apk size almost doubles

### ISSUE THREAD

**Issue by JeremyBradshaw7** [christopherdro/react-native-html-to-pdf#117]
Comparing the android .apk before and after adding this project, 8.7MB have been added as evidenced by a new tom_roush folder containing loads of font assets:

![image](https://user-images.githubusercontent.com/36155348/54473686-f758b180-47d2-11e9-9320-7befb5aacac0.png)

Is this necessary? Can it be reduced? I notice that the corresponding iOS .ipa file has increased hardly at all.

**Comment by guidux** [comment]
I just noticed that tom_rush folder is duplicated in fact:

![image](https://user-images.githubusercontent.com/1030759/59716009-13f5f280-91e3-11e9-8d40-ccbb110a0949.png)

So far I couldn't get rid off any of them.

**Comment by hannanstd** [comment]
hi
i have this problem. there are 2 tom_roush with big size and propably one of them is extra.

**Comment by ashutoshpathak200** [comment]
@JeremyBradshaw7 @guidux did you find a solution to this?

**Comment by JeremyBradshaw7** [comment]
@ashutoshpathak200 no, but we're no longer using this package, having moved pdf generation to the backend.

**Comment by Daniel0liver** [comment]
> hi
> i have this problem. there are 2 tom_roush with big size and propably one of them is extra.

where can i find these duplicate folders?

**Comment by ViniciusPaldes** [comment]
Same here, two folders of 2.9mb in a total of 5.8mb. 

Considering our app size 16Mb, this lib takes around 30% of apk size.

<img width="1277" alt="Screen Shot 2020-06-08 at 18 58 52" src="https://user-images.githubusercontent.com/2675050/84084631-323b9c00-a9ba-11ea-805d-1f7e653e5fe9.png">

**Comment by Daniel0liver** [comment]
> Mesmo aqui, duas pastas de 2,9mb em um total de 5,8mb.
> 
> Considerando o tamanho do aplicativo 16Mb, essa lib ocupa cerca de 30% do tamanho do apk.
> 
> <img alt="Captura de tela 2020-06-08 às 18 58 52" width="1277" src="https://user-images.githubusercontent.com/2675050/84084631-323b9c00-a9ba-11ea-805d-1f7e653e5fe9.png">

unfortunately I never received an answer about this problem again, here at @mobills we had to live with this problem, others had to generate pdf on the back end.

**Comment by haresh4d** [comment]
Did anyone find solution here? I am having the same issue and I can not use backend to generate pdf. Please help.

**Comment by shubhamdeol** [comment]
I have found a solution to this. Solution is not to use this package.

1- Install expo-unimodules to react native app
https://docs.expo.io/bare/installing-unimodules/

2- ```yarn add expo-print```

3- use expo-print
```js
import * as Print from 'expo-print';

 //somewhere in your code
const result = await Print.printToFileAsync({
        html: getHtmlReportString(data),
      });

result is file uri
```
Read doc for expo print here:  
https://docs.expo.io/versions/latest/sdk/print/

**Comment by Daniel0liver** [comment]
this problem has been fixed here [react-native-html-to-pdf-custom](https://www.npmjs.com/package/react-native-html-to-pdf-custom)

**Comment by Onibenjo** [comment]
You could try [react-native-html-to-pdf-lite](https://www.npmjs.com/package/react-native-html-to-pdf-lite)
