### ISSUE TITLE
Duplicated modules

### ISSUE THREAD

**Issue by ramonscampos** [christopherdro/react-native-html-to-pdf#119]
Every time I run yarn/npm install, a node_modules folder is created inside example folder from the lib: node_modules > react-native-html-to-pdf > example > node_modules..

So when I try to run the app, it crashes..
"This error is caused by a @providesModule declaration with the same name across two different files."

When I delete the example folder, the app runs normally..

There is any way to avoid delete folder every time I run yarn/npm install?

**Comment by SimonErm** [comment]
#110
