### ISSUE TITLE
react-native-html-to-pdf  collides react-native

### ISSUE THREAD

**Issue by danielsouzapinna** [christopherdro/react-native-html-to-pdf#124]
Hi all,

When I installed the react-native-html-to-pdf package, I received the error below:

Duplicate module name: Sample
  Paths: C: \ projects \ signature-electronics \ node_modules \ react-native-html-to-pdf \ example \ node_modules \ react-native \ Libraries \ Sample.config.json collides with C: \ projects \ signature-electronics \ node_modules \ react-native \ Libraries \ Sample \ package.json

Can you rename the dir "react-native-html-to-pdf\example\node_modules\react-native\ Libraries\Sample" to another name to avoid this error?

Thanks

**Comment by MarcosSarges** [comment]
I have the same problem T-T

**Comment by SimonErm** [comment]
#110

**Comment by williamhqs** [comment]
I got a very familiar error, it's `react-animated`

```
Loading dependency graph...(node:13027) UnhandledPromiseRejectionWarning: Error: jest-haste-map: Haste module naming collision:
  Duplicate module name: react-animated
  Paths: /A/RNCreatePDF/node_modules/react-native-html-to-pdf/example/node_modules/react-native/Libraries/Animated/release/package.json collides with /A/RNCreatePDF/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by `hasteImpl` returning the same name for different files.
    at setModule (/A/RNCreatePDF/node_modules/jest-haste-map/build/index.js:569:17)
    at workerReply (/A/RNCreatePDF/node_modules/jest-haste-map/build/index.js:641:9)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:13027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

```

**Comment by SpyderScrypt** [comment]
None of the above works for me.... is there any easy solution?

**Comment by MarcosSarges** [comment]
what was the mistake?

**Comment by GreenRidingHood** [comment]
nothing worked with me either, 
i am following https://github.com/christopherdro/react-native-html-to-pdf/issues/98 
issue#98 too, but it did not help either.

@SpyderScrypt did you find any solution?

**Comment by GreenRidingHood** [comment]
that solution helped me, now i get apk successfully

https://github.com/facebook/react-native/issues/19239#issuecomment-393898039

**Comment by coucoseth** [comment]
My solution :

Delete node modules folder and run "npm i" in the terminal to reinstall node modules.
This solved this same issue i was facing
