### ISSUE TITLE
Setting A4 format adds an extra page

### ISSUE THREAD

**Issue by krstffr** [christopherdro/react-native-html-to-pdf#126]
I tried setting the width/height to 595 × 842 points as suggested here https://www.prepressure.com/library/paper-size/din-a4. This however adds an extra empty page (with just the background color) to the PDF, probably because of some margin/padding stuff?

Attached here is an [example.pdf](https://github.com/christopherdro/react-native-html-to-pdf/files/3157377/example.pdf) using these options, note the two pages:
```
{
  padding: 0,
  height: 842,
  width: 595,
  html: "<h1>Test</h1>"
}
```

**Comment by liamjones** [comment]
I was encountering this too and was initially using the same page for reference. There's no problem with this project, the reference page is actually incorrect. That page is rounding the length up to the nearest whole point, making it longer than an A4 page.

**Comment by krstffr** [comment]
Yeah, makes sense.

(I actually switched over to pdfkit which gave me way more (and precise!) control.)
