### ISSUE TITLE
Features : get the pdf file in base64

### ISSUE THREAD

**Issue by Nicolas-Menettrier** [christopherdro/react-native-html-to-pdf#13]
Hello,
I would like to know if getting the pdf file in base64 with an option is envisaged ? For sending base64 pdf in an API for example.

EDIT: I made this features for iOS if someone is interested.

**Comment by neverlan** [comment]
Hey :)

I'm interested if you would like to share :)

**Comment by Nicolas-Menettrier** [comment]
All in the zip file, replace your RNHTMLtoPDF.m by this one :)

How it works : 

```
var options = {
      html: html,
      height: 1300,
      width: 800,
      padding: 40,
      base64: true,  // <== new options
      fileName: 'test',
      directory: 'docs',
}
RNHTMLtoPDF.convert(options).then((data) => {
   console.log(data.filePath);
   console.log(data.base64);
});

// if base64 is set to false data.base64 will be an empty string
```

[RNHTMLtoPDF.zip](https://github.com/christopherdro/react-native-html-to-pdf/files/541657/RNHTMLtoPDF.zip)

**Comment by neverlan** [comment]
Thanks a lot :)

I’ll take a look tonight.

**Comment by christopherdro** [comment]
@Nicolas-Menettrier Any chance you would like to turn that into a pull request?
