### ISSUE TITLE
Link in PDF not work for iOS

### ISSUE THREAD

**Issue by rogerionj** [christopherdro/react-native-html-to-pdf#130]
An HTML with link (<a href= "http://google.com">Teste</a>), while generating the PDF link within the PDF works only for Android. In iOS it removes the link being just text. Any solution for this?

**Comment by SpawnAtis** [comment]
@rogerionj Hi. Did you find any solution ?

**Comment by hiren2728** [comment]
Facing the same issue.
@rogerionj @SpawnAtis  Did you find any solution for it

**Comment by viniciusaugutisps** [comment]
Good night! Someone resolve this? I am with problem in Android, the hyperlinks don`t work
