### ISSUE TITLE
null is not an object

### ISSUE THREAD

**Issue by hunghoang179** [christopherdro/react-native-html-to-pdf#131]
Hello guys!
Today im try create project width react native (for iOS). When i using react-native-html-to-pdf then get error 

> null is not an object (evaluating '_reactNativeHtmlToPdf.default.convert').

I did follow issue #80, but can't resolve. 
Who can help me how to fix this?

```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-html-to-pdf": "^0.7.0"
  },
```

Thank you so much!

**Comment by christopherdro** [comment]
Are you sure you've linked the files properly? 
If you are using Expo and haven't ejected this library will not work.

**Comment by khanisak** [comment]
I got this error on fresh installation react native projects.

`
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-html-to-pdf": "^0.8.0"
  },`

either automatic link with `react-native link` and manual link provided in documentation doesn't work.
Does this package support react native auto link?

**Comment by khanisak** [comment]
I solved this issue by re-install my apps after install this package. Thank you.

**Comment by giancarlohorta** [comment]
how do i make the manual link on Expo?

**Comment by anastely** [comment]
I faced the same and I re-install the app as u say @khanisak

**Comment by Mubeyd** [comment]
> I solved this issue by re-install my apps after install this package. Thank you.
I put it in import { RNHTMLtoPDF }  and reinstalled the app and finally did not work :(

**Comment by alitsvin** [comment]
Solved the issue for android by reinstall the app
For ios `pod install` in ios folder helped

**Comment by lucaspiressimao** [comment]
I have the same problem but reinstall did not solve my problem. Any ideas ?

**Comment by MuhammadRafeh** [comment]
I am also stuck in this problem. Can any one guide how to link expo with react native modules  and how to solve this problem.

**Comment by ananyalohani** [comment]
I'm facing the same error, using this with Expo. Could the maintainers help me out?

**Comment by Raidro** [comment]
I was with the same issue and in my case to resolve this I installed a library after that I applied `react-native link` and solved! I also deleted `node_modules` and reinstalled them.

**Comment by aakarshan-raj** [comment]
you need to restart your metro server after installing the package.
