### ISSUE TITLE
[DOCUMENTATION] File Permission

### ISSUE THREAD

**Issue by maxjf1** [christopherdro/react-native-html-to-pdf#134]
I couldn't use the lib at all, because it always crashes the app (and without error logs)

i figured it out asking for `WRITE_EXTERNAL_STORAGE` permissions on the app with [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid). 

I'm new to native, so maybe this is an well-known fact. but would be great to add it on the documentation.

**Comment by rashidul-hasan** [comment]
#150
