### ISSUE TITLE
 IOS Error : UI API called on a background thread

### ISSUE THREAD

**Issue by jsuryahyd** [christopherdro/react-native-html-to-pdf#135]
**Version** : 0.8.0
**RN version** : 0.60.5
using **cocoapods**

**Code:**
```
let file = await RNHTMLtoPDF.convert(options).catch(err =>
    console.error(err)
  );
```

**Error:**
```
[_webView loadHTMLString:_html baseURL:baseURL] 
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
```
Resolved the error by enclosing the line with `dispatch_async`,
- line 176, `RNHTMLtoPDF.m`
```
dispatch_async(dispatch_get_main_queue(), ^{
    [_webView loadHTMLString:_html baseURL:baseURL];
});
```
Not sure if this is a bug with the library, and if this is the valid way. Am I the only one getting this error?

**Comment by elisechant** [comment]
I am also getting the same notification, ..but the app still works after some time. 

<img width="927" alt="Screen Shot 2019-09-17 at 12 38 04 pm" src="https://user-images.githubusercontent.com/2195815/65006978-09650980-d948-11e9-94d5-622ef57fba4b.png">

**Comment by LeoLeBras** [comment]
I have the same problem, it only appears with iOS 13.

**Comment by Finneah** [comment]
> **Version** : 0.8.0
> **RN version** : 0.60.5
> using **cocoapods**
> 
> **Code:**
> 
> ```
> let file = await RNHTMLtoPDF.convert(options).catch(err =>
>     console.error(err)
>   );
> ```
> 
> **Error:**
> 
> ```
> [_webView loadHTMLString:_html baseURL:baseURL] 
> Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
> ```
> 
> Resolved the error by enclosing the line with `dispatch_async`,
> 
> * line 176, `RNHTMLtoPDF.m`
> 
> ```
> dispatch_async(dispatch_get_main_queue(), ^{
>     [_webView loadHTMLString:_html baseURL:baseURL];
> });
> ```
> 
> Not sure if this is a bug with the library, and if this is the valid way. Am I the only one getting this error?

I am getting the same error, thanks for the temporary solution!
