### ISSUE TITLE
Converting a HTML page to PDF on IOS causes app freeze

### ISSUE THREAD

**Issue by nikitpanchal** [christopherdro/react-native-html-to-pdf#136]
When converting small Html page (one A4 Page size) it works fine, but when converting large html (2 Pages of A4) it freeze app on IOS
Works fine on Android

**Comment by tuan23** [comment]
We are experiencing the same issue, the app is frozen (but not crashes) when converting html to pdf (for about 5 seconds). Could you have a look?

**Comment by ivangr1** [comment]
Same here. I am testing it on iPhone 6 and it takes almost half a minute to generate a pdf with simple title and table with 3 cells. Android works fine. Can anybody identify the issue?
