### ISSUE TITLE
Publishing on App store is blocked because of UiWebView

### ISSUE THREAD

**Issue by Ludixx** [christopherdro/react-native-html-to-pdf#138]
Hi,

I tried to submit my app to AppStore but I got an e-mail showing this :

> ITMS-90809: Deprecated API usage - Apple will stop accepting submissions of apps that use UIWebView APIs.

I found this article on the RN site :
[https://facebook.github.io/react-native/blog/2018/08/27/wkwebview](url)

It is said that UIWebView has to be replaced by WKWebView.

Im new to react native but I could help in this changes.
My app needs to be published as soon as possible so if you need help Im here !

Thanks in advance !

Ludovic Prime

**Comment by LeoLeBras** [comment]
This looks interesting ➡️ https://github.com/patelgaurav4u/html-to-pdf-react-native

**Comment by christopherdro** [comment]
Fixed via
