### ISSUE TITLE
npm install in Example folder has lots of warnings and errors

### ISSUE THREAD

**Issue by joshloo** [christopherdro/react-native-html-to-pdf#14]
Hi Christopher,

Thanks for creating this module. I am eager to try out. I noticed that the npm install has several errors on gyp-build. And after npm install, I run "react-native run-ios" and i got the error below:

(node:4626) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Command `run-ios` unrecognised

Did I miss anything?

**Comment by joshloo** [comment]
I tried to update the version in package.json to 
"react": "^15.3.1",
"react-native": "^0.33.0",
"react-native-html-to-pdf": "0.1.3",
then run "react-native run-ios", the compilation failed with error:

** BUILD FAILED **
The following build commands failed:
	CompileC build/Build/Intermediates/HTMLToPDFExample.build/Debug-iphonesimulator/HTMLToPDFExample.build/Objects-normal/x86_64/AppDelegate.o HTMLToPDFExample/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/HTMLToPDFExample.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/HTMLToPDFExample.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by christopherdro** [comment]
@joshloo New version has an example app from React Native 0.40
https://github.com/christopherdro/react-native-html-to-pdf/releases/tag/v0.3.0
