### ISSUE TITLE
Padding Top bottom left right not Working properly. 

### ISSUE THREAD

**Issue by nikitpanchal** [christopherdro/react-native-html-to-pdf#141]
Hello,
I have a HTML and trying to convert it to PDF which is working fine. 
Now i have some dynamic padding values which im passing as below : 

```
let options = {
        html: myHtml,
        fileName: 'random_' + dname,
        base64: true,
     
        bgColor: '#FFFFF',
        paddingRight:  parseInt(settings[1]) * 1.35 , //Right
        paddingLeft: parseInt(settings[0]) * 2, //Top
        paddingTop: parseInt(settings[3]) * 1.35,//Left,
        paddingBottom: parseInt(settings[2]) * 1.35, //Bottom


      };
```
Now if you see my comment next to padding Values, when assigning value to paddingTop it pads from Left and when assigning value to padding Left it pad from Top. 

And when assigning to value only for paddingLeft (for me its Top) it pads from both side Top and Right.
Its weird 
Please help me

**Comment by NeilMcGuiness** [comment]
+1 to this issue, also experiencing this.
