### ISSUE TITLE
how to install on react-native > v0.61

### ISSUE THREAD

**Issue by agrapana** [christopherdro/react-native-html-to-pdf#146]
i tried to install and input the details in :
1. android/settings.gradle
2. android/app/build.gradle
3. MainApplication.java

but i cannot run my application.

and then i thought the link is automatically, so i tried re install again and run the apps immediately, 
but i still cannot run my application. It gives me both : 
```
Task :react-native-html-to-pdf:compileDebugJavaWithJavac

> Task :app:mergeDebugAssets FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
```

could you please help me?
thanks

**Comment by thuytony** [comment]
anyone has solution for this? i got same issues :(
