### ISSUE TITLE
Custom Save Directory - Error: RNHTMLtoPDF error: Could not create folder structure.

### ISSUE THREAD

**Issue by adonaipinheiro** [christopherdro/react-native-html-to-pdf#149]
"react-native": "0.59.9",
"react-native-html-to-pdf": "^0.8.0"

let options = {
      html: `${s.data.receipt.receiptformatted}`,
      fileName: `comprovante-multify-${s.data.transactionId}`,
      directory: `${RNFS.ExternalStorageDirectoryPath}/Downloads`,
    };

I´ve tried to put only 'docs' or 'downloads', same problem. Any help?

I´ve tried without RNFS too.

**Comment by christopherdro** [comment]
> Directory where the file will be created (Documents folder in example above). Please note, on iOS Documents is the only custom value that is accepted.

**Comment by adonaipinheiro** [comment]
Its saving on cache by default. And if i change to any other thing, doesnt save. "Cannot create folder struture", something like that.

**Comment by matias4205** [comment]
For anyone who is having this same issue, it is a permission error. Try giving storage permissions in the app configuration manually, or see this tutorial where it's explained how to do it programmatically: [](https://aboutreact.com/make-pdf-in-react-native-from-html-text/)

**Comment by DnEgorWeb** [comment]
For anyone having same issue with newer versions of react-native: https://github.com/christopherdro/react-native-html-to-pdf/issues/189

**Comment by Piyush132000** [comment]
Possible Unhandled Promise Rejection (id: 0):
Error: RNHTMLtoPDF error: Could not create folder structure.
promiseMethodWrapper@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2242:45
createPDF$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:282119:86
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25281:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25454:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25281:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25354:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25364:21
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27355:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27456:27
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30895:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30934:17
callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31151:33
__callImmediates@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2736:35
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2522:34
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2719:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:2521:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]




Hello friends , i am getting this error please help me .

**Comment by Bilal-Abdeen** [comment]
Please, check my comment https://github.com/christopherdro/react-native-html-to-pdf/issues/189#issuecomment-849999309
