### ISSUE TITLE
Android support not working

### ISSUE THREAD

**Issue by joshloo** [christopherdro/react-native-html-to-pdf#15]
Instruction mentioned adding 
include ':react-native-html-to-pdf'
project(':react-native-html-to-pdf').projectDir = new File(rootProject.projectDir,'../node_modules/react-native-html-to-pdf/android')

But there's no ./node_modules/react-native-html-to-pdf/android folder.

**Comment by joshloo** [comment]
After manually copying the android folder over, the gradle build is complaining about unable to resolve symbol RNHTMLtoPDFPackage in MainApplication.java

**Comment by parkerdan** [comment]
@joshloo @christopherdro , there's a typo in Read Me.  This line

`project(':react-native-html-to-pdf').projectDir = new File(rootProject.projectDir,'../node_modules/rreact-native-html-to-pdf/android')`

has an extra `r` in `node_modules/rr  <---  OOPS  `  should be `node_modules/react-native-html-to-pdf/android`

My bad

**Comment by parkerdan** [comment]
I literally just created a new project, npm installed the package, and everything built just fine.

**Comment by joshloo** [comment]
@parkerdan  Yeah I have fixed that before filing this issue. I still could not get it to run on my project with the same error on resolving symbol for RNHTMLtoPDFPackage. Can you please share your sample project that is working for Android in the Example folder?

**Comment by parkerdan** [comment]
@joshloo...Delete the node module, follow the installation steps, if it does not work, you must be doing something wrong.  Like I said.  I created a new project, followed the steps, and everything worked.

**Comment by christopherdro** [comment]
@joshloo Ever get this working?

**Comment by christopherdro** [comment]
New version has this typo fixed including new features that have been tested.
https://github.com/christopherdro/react-native-html-to-pdf/releases/tag/v0.3.0
