### ISSUE TITLE
UIWebViews discontinued by ios

### ISSUE THREAD

**Issue by youstronsic** [christopherdro/react-native-html-to-pdf#151]
This library is using the depreciated UIWebViews , i'm getting following warning while uploading to ios store

**_ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs ._**

I request the community to update this library with the new react native webview i.e _wkWebView_. 
If anyone know how to shift from UiWebView to WkWebView then please comment.

**Comment by stepupithub** [comment]
hey there ???? i'm also using this library and getting that mail too @youstronsic

**Comment by youstronsic** [comment]
@stepupithub 
check the following link it has two files, replace these files with your project's file (node_modules/react-native-html-to-pdf/ios/RNHTMLtoPDF/)
https://github.com/christopherdro/react-native-html-to-pdf/tree/master/ios/RNHTMLtoPDF

**Comment by mohankoppuravuri** [comment]
Can you please make a release into npm registry. so that with 'npm ci' command we can get this code.

**Comment by maitcc** [comment]
please :(

**Comment by mohankoppuravuri** [comment]
How to link this module to native modules if we download and use it  as a library. (not through npm).

**Comment by vadavallipavan** [comment]
Can you please advise when can this updated be pushed to NPM registry . Deadline has passed and Apple is rejecting the updates

**Comment by mohankoppuravuri** [comment]
> Can you please advise when can this updated be pushed to NPM registry . Deadline has passed and Apple is rejecting the updates

Use this module as the local module.

**Comment by vadavallipavan** [comment]
> please :(

As suggested in another thread ,used the below option, worked fine for me..
In your package.json, replace the 0.8.0 with the GitHub address like this:
"react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf.git",

**Comment by mcvictormurillo** [comment]
Hello developers, I have created a guide to solve the problem https://www.notion.so/iOS-Deprecated-API-UIWebView-623e2131bf014871849b300f2296c99a

**Comment by nodejs-express** [comment]
Hey man,

thanks. But i found and an bug in RNHTMLtoPDF.m file. Its in lin 177, it should be: dispatch_async(dispatch_get_main_queue(), ^{
        [self->_webView loadHTMLString:**self->_html baseURL:baseURL];**
    });
