### ISSUE TITLE
Crash on Android 10

### ISSUE THREAD

**Issue by mjm918** [christopherdro/react-native-html-to-pdf#158]
My clients who are using android 10, are facing the following issue:

```
java.lang.IllegalArgumentException: 
  at On.onWrite (PG:27)
  at android.print.PdfConverter$1.onPageFinished (PdfConverter.java:71)
  at e6.b (PG:2)
  at on.handleMessage (PG:63)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7770)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1047)
```

After seeing this trace, the first thing came to my mind that maybe the user did not allow storage permission. I double checked with them and found out that the storage permission was enabled. However, when the app is trying to generate PDF, it crashes. 

Any ideas? Thank you

**Comment by mjm918** [comment]
Any update on this? Any workaround or solution? Thank you

**Comment by SaruwatariSagittario** [comment]
Hi, just realise i'm also facing similar issue regarding Permission. But, it's kinda random though. sometimes the crash happened sometimes not.

**Comment by mjm918** [comment]
@SaruwatariSagittario do you face this issue in android 10 also?

**Comment by SaruwatariSagittario** [comment]
Yes.
Scratching head for days cause of the crash. I already put the permission protocol using react-native-permissions before generating pdf, still Crashes on Android 10

**Comment by mjm918** [comment]
It's not about permission.. I have tried granting the permission manually from settings but still crashes.

https://github.com/christopherdro/react-native-html-to-pdf/blob/4bc1a3d249ede0329d4de3aaa72bd3b6db7d2ef1/android/src/main/java/android/print/PdfConverter.java#L71

this is the line where it crashes.

**Comment by SaruwatariSagittario** [comment]
Yeah I also got logcat report saying it stopped working on that particular line. Do your issue happen intermittently or always happened.

**Comment by mjm918** [comment]
for me it happens every time 😕

**Comment by VesperHan** [comment]
Same issue, but I cannot find some way to work around

**Comment by TiagoCoelhoB** [comment]
i changed sdk to sdk 29, and added this line:
PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
to index.

**Comment by mjm918** [comment]
for me the solution was, save the pdf file in an existing directory.. Seems like if we dont specify the directory, the lib cant save the file. 

NOTE: I asked for directory permission but still faced the issue. Specifying an existing directory solved my problem.

**Comment by rusliabdulgani** [comment]
hi, any update about this issue??

**Comment by zsy6504** [comment]
Has anybody got a solution yet?

**Comment by zsy6504** [comment]
After searching through github repo fork network graph, I found this fork works fine: https://github.com/jdaoliveira/react-native-html-to-pdf
For anybody who's suffering the android 10 upgrade, you can uninstall version 0.8.0 and try `npm install https://github.com/jdaoliveira/react-native-html-to-pdf.git`
