### ISSUE TITLE
Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

### ISSUE THREAD

**Issue by JintoAntony** [christopherdro/react-native-html-to-pdf#162]
Installed the plugin. Then when I try to take a build, it shows the following error

`> Task :react-native-html-to-pdf:compileDebugJavaWithJavac

> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
175 actionable tasks: 24 executed, 151 up-to-date
Note: /Users/prime/Dropbox/Development/Donams/E-Sell-MobileApp/node_modules/react-native-html-to-pdf/android/src/main/java/android/print/PdfConverter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D8: Cannot fit requested classes in a single dex file (# methods: 84050 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

Any idea how to fix this ?

"react": "16.9.0",
"react-native": "0.61.5",
"react-native-html-to-pdf": "^0.8.0",

**Comment by sagarrs** [comment]
same issue any solution ?

**Comment by rikur** [comment]
I fixed this by upgrading mindSdkVersion to 21 for my app and all subprojects and by enabling multiDex

android/build.gradle
```
buildscript {
    ext {
        minSdkVersion = 21
..

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                minSdkVersion = 21
            }
        }
    }
}
```

android/app/build.gradle
```
android {
    defaultConfig {
        multiDexEnabled true
```
