### ISSUE TITLE
No return on RNHTMLtoPDF.convert()

### ISSUE THREAD

**Issue by Finneah** [christopherdro/react-native-html-to-pdf#163]
We need to create a PDf with multiple images and some data.  On the End the file has more then 10 Sites. If we create a smaller file it works without problems. 
On iOS it works fine but its not working  on android with bigger files. 

`RNHTMLtoPDF.convert(options);` do not return and the app stuck.

Do you have any idea how to fix that?

**Comment by MahbbRah** [comment]
I think Same issue facing here! Returning but Dummy page. with no data inside the PDF.

**Comment by ReactDevs007** [comment]
Let me know if you have still problems.
I can help. My email 
kreactdev@gmail.com

**Comment by lucaspiressimao** [comment]
Same here.... no return from convert even using a dummy html

let options = {
                html: '<h1>test</h1>',
                fileName: 'test',
                directory: 'test',
            }

**Comment by lucaspiressimao** [comment]
> Same here.... no return from convert even using a dummy html
> 
> ```
> let options = {
>                 html: '<h1>test</h1>',
>                 fileName: 'test',
>                 directory: 'test',
>             }
> ```

Log from logical

```
08-11 19:03:54.877 28911 28911 D PdfConverter: Failed to open ParcelFileDescriptor
08-11 19:03:54.877 28911 28911 D PdfConverter: java.io.IOException: Permission denied
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.io.File.createNewFile(File.java:1008)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.print.PdfConverter.getOutputFileDescriptor(PdfConverter.java:135)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.print.PdfConverter.access$100(PdfConverter.java:33)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.print.PdfConverter$1.onPageFinished(PdfConverter.java:71)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at oo.b(chromium-Monochrome.aab-stable-414711173:2)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at ky0.handleMessage(chromium-Monochrome.aab-stable-414711173:66)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.os.Looper.loop(Looper.java:193)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.app.ActivityThread.main(ActivityThread.java:6762)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
``

> Same here.... no return from convert even using a dummy html
> 
> ```
> let options = {
>                 html: '<h1>test</h1>',
>                 fileName: 'test',
>                 directory: 'test',
>             }
> ```

Log from logical

```
08-11 19:03:54.877 28911 28911 D PdfConverter: Failed to open ParcelFileDescriptor
08-11 19:03:54.877 28911 28911 D PdfConverter: java.io.IOException: Permission denied
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.io.File.createNewFile(File.java:1008)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.print.PdfConverter.getOutputFileDescriptor(PdfConverter.java:135)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.print.PdfConverter.access$100(PdfConverter.java:33)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.print.PdfConverter$1.onPageFinished(PdfConverter.java:71)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at oo.b(chromium-Monochrome.aab-stable-414711173:2)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at ky0.handleMessage(chromium-Monochrome.aab-stable-414711173:66)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.os.Looper.loop(Looper.java:193)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at android.app.ActivityThread.main(ActivityThread.java:6762)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-11 19:03:54.877 28911 28911 D PdfConverter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


08-11 19:03:54.881 28911 28911 E AndroidRuntime: java.lang.IllegalArgumentException: fd cannot be null
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at Ny0.onWrite(chromium-Monochrome.aab-stable-414711173:28)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at android.print.PdfConverter$1.onPageFinished(PdfConverter.java:71)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at oo.b(chromium-Monochrome.aab-stable-414711173:2)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at ky0.handleMessage(chromium-Monochrome.aab-stable-414711173:66)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6762)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-11 19:03:54.881 28911 28911 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by lucaspiressimao** [comment]
@Finneah @MahbbRah 

I had the same problem and the fix was just a permission that we should ask.

something like this should solve the problem.

```
let grantedConst = PermissionsAndroid.RESULTS.GRANTED

            try {
                const grantedRead = await PermissionsAndroid.request(
                  PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
                  {
                    title: "PDF PERMISSION",
                    message: "App need access ",
                    buttonNeutral: "Latter",
                    buttonNegative: "Cancel",
                    buttonPositive: "OK"
                  }
                );

                const grantedWrite = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                    {
                    title: "PDF PERMISSION",
                    message: "App need access ",
                    buttonNeutral: "Latter",
                      buttonNegative: "Cancel",
                      buttonPositive: "OK"
                    }
                  );

                
                if (grantedRead === grantedConst && grantedWrite === grantedConst) {
                    generatePDF()
                } else {
                  console.log("permission denied");
                }
              } catch (err) {
                console.warn(err);
              }
```

**Comment by Finneah** [comment]
@lucaspiressimao Thanks for the Tip, but we had to choose another library. We couldn't wait that long because this is an important part of our app. If I remember correctly I had this permission query.

**Comment by schmidtmc** [comment]
> @lucaspiressimao Thanks for the Tip, but we had to choose another library. We couldn't wait that long because this is an important part of our app. If I remember correctly I had this permission query.

What other library did you find that does html to pdf?
