### ISSUE TITLE
iOS WebView to WebKit not on Release

### ISSUE THREAD

**Issue by marvinPlasmatic** [christopherdro/react-native-html-to-pdf#166]
**Issue**
Latest release does not include the changes to iOS WebView to Webkit.

**Comment by lylong90** [comment]
Any updates on this issue? Or can anyone please suggest a workaround?

**Comment by marvinPlasmatic** [comment]
> Any updates on this issue? Or can anyone please suggest a workaround?

For a workaround you can download it and manually link it.
