### ISSUE TITLE
Apple doesn't allow UIWebView - can you remove it or make mobile version?

### ISSUE THREAD

**Issue by craftmusic** [christopherdro/react-native-html-to-pdf#168]
After submitting my app on TestFlight, I got this response; I searched my xcode files and found your library was the culprit :) Any solution?

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by Thurs10dev** [comment]
Yeah, this library isn't really useful if Apple can't approve apps that use it. Any help or workarounds would be much appreciated.

**Comment by reactdevrocks** [comment]
so what can we do for that still is we are installing it shows version 0.8.0 and not having your fixes on this version. so what to do?

**Comment by craftmusic** [comment]
> so what can we do for that still is we are installing it shows version 0.8.0 and not having your fixes on this version. so what to do?

In your package.json, replace the 0.8.0 with the GitHub address like this:

 "react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf.git",

**Comment by craftmusic** [comment]
I did that and I no longer get the warning from Apple about the deprecated package. 

I’ll leave this issue open though as a reminder for the owners to update npm 🙂

**Comment by vadavallipavan** [comment]
i did the same and the application went through...

> > so what can we do for that still is we are installing it shows version 0.8.0 and not having your fixes on this version. so what to do?
> 
> In your package.json, replace the 0.8.0 with the GitHub address like this:
> 
> "react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf.git",

It worked for me as well,  Thanks for the updates, once the npm is updated, just need to use the latest version.

**Comment by christopherdro** [comment]
Update released in v0.9.0
