### ISSUE TITLE
Cannot convert to pdf when emoji in html on android

### ISSUE THREAD

**Issue by sylv1b** [christopherdro/react-native-html-to-pdf#171]
When trying to convert html containing emoji (⭐ this one, i didn't try with others but I assume it's the same) the output is "undefined".

**Comment by christopherdro** [comment]
There was a small change merged recently to address images on android that might also resolve the issue with rendering emojis. https://github.com/christopherdro/react-native-html-to-pdf/pull/108/files#diff-47032573b1dcb4f7848207a31c50c919ab0e9ec012ce71f2c47edafcc5183e3bR99

Can you try the release v0.9.0 and see if that solves the problem?
