### ISSUE TITLE
Support for padding on Android

### ISSUE THREAD

**Issue by kenodek** [christopherdro/react-native-html-to-pdf#172]
There is always default padding on Android and there is no way to remove/change it. It's really frustrating

**Comment by shoki61** [comment]
yes it's a big issue, i am frustrated,too. I also came here to write this.

**Comment by kenodek** [comment]
Does somebody has an idea why it is like that and what is the way to solve it?

**Comment by shoki61** [comment]
i found it, write this code:

`html : '<style>
    @page{
    background-color: red;
    margin-left: 0pt;
    margin-right: 0pt;
    margin-top: 0pt;
    margin-bottom: 0pt;
    padding-left: 0pt;
    padding-right: 0pt;
    padding-top: 0pt;
    padding-bottom: 0pt;
    }
    </style>'`

adjust the values as you want.
