### ISSUE TITLE
IOS ITMS-90809: Deprecated API Usage warning

### ISSUE THREAD

**Issue by vrautgit** [christopherdro/react-native-html-to-pdf#175]
Thank you for this amazing library. Feature dependant on the library is working really well except this minor bug.

When I submit the app on app-store I am getting the following warning:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020.

I tried implementing a solution from following link: 
[https://github.com/christopherdro/react-native-html-to-pdf/issues/151#issuecomment-569597226](https://github.com/christopherdro/react-native-html-to-pdf/issues/151#issuecomment-569597226)

After implementing this solution warning from app-store goes but I am getting these two issues:
1. Images from local cache are not shown in PDF
2. Font from local cache are not shown in PDF

Also, I am not facing the above issues on the simulator. I tried running the build in release mode and on various versions of the simulator.

Thanks in advance for the help.

**Comment by wootwoot1234** [comment]
Did you find a solution to this?   I'm having the same issue.  Thanks!

**Comment by vadavallipavan** [comment]
As suggested in another thread ,used the below option, worked fine for me..

In your package.json, replace the 0.8.0 with the GitHub address like this:

"react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf.git",

**Comment by vrautgit** [comment]
> As suggested in another thread ,used the below option, worked fine for me..
> 
> In your package.json, replace the 0.8.0 with the GitHub address like this:
> 
> "react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf.git",

With this solution also, I am still not seeing images from cache and font from cache on pdf.

**Comment by vrautgit** [comment]
As I was not able to get an image from the local cache load into pdf I did one workaround.
I converted images into base64 and then loaded it into the app.

But I am still facing the issue with local cache font.

**Comment by christopherdro** [comment]
Update released in v0.9.0
