### ISSUE TITLE
How to pass data from react native to html content and receive data from html to react native

### ISSUE THREAD

**Issue by sagarrs** [christopherdro/react-native-html-to-pdf#176]
Hi i am making a API call in react native **i want to pass the response of that API call to html and receive data from html to react native** can someone please tell me how to achieve it ? there is no "options" to send or receive data.

```
import React, { Component } from 'react';
import {Text,TouchableHighlight,View,} from 'react-native';
import RNHTMLtoPDF from 'react-native-html-to-pdf';
import htmlContent from './htmlContent'

export default class Example extends Component {
  state = {
      apiData : []  
  }

  componentDidMount(){
      fetch(`http://API`)
          .then((response) => response.json())
          .then((responseJson) => {
              **console.log("DATA", responseJson) // NEED TO SEND THIS DATA TO "HTML"**
              this.setState(() => ({
                  apiData: responseJson
              }))
        })
  }

  async createPDF() {
    let options = {
      **html: htmlContent,**
      fileName: 'test',
      directory: 'Documents',
    };

    let file = await RNHTMLtoPDF.convert(options)
    // console.log(file.filePath);
    alert(file.filePath);
  }

  render() {
    return(
      <View>
        <TouchableHighlight onPress={this.createPDF}>
          <Text>Create PDF</Text>
        </TouchableHighlight>
      </View>
    )
  }
}
```

**Comment by andreepratama27** [comment]
You can pass the data to html pages. First in first you must return a `function`. The code look like this:

const htmlFiles = data => `
  <h1>{data.name</h1>
`
and put this in your code

`
async createPDF() {
    const dataToparse = {name: 'testing'}

    let options = {
      html: htmlFiles(dataToParse),
      fileName: 'test',
      directory: 'Documents',
    };

    let file = await RNHTMLtoPDF.convert(options)
    // console.log(file.filePath);
    alert(file.filePath);
  }

  render() {
    return(
      <View>
        <TouchableHighlight onPress={this.createPDF}>
          <Text>Create PDF</Text>
        </TouchableHighlight>
      </View>
    )
  }
`

**Comment by 14BCS1464** [comment]
Here is the solution


const createpdf=()=>{ options = {
            html:htmlForInvoice("Sunil","praja@gmail.com","8437513006","$100"),
            fileName: 'tGenieInvoice_' + uuid.v4(),
            directory: 'Documents',
        };

        try {
            let file = await RNHTMLtoPDF.convert(options)
            console.log(file.filePath);
            openGeneratedPDF(file.filePath, 'application/pdf');
        } catch (err) {
            console.error(err)
        }

}

export default function htmlForInvoice(
  name: string,
  email: string,
  phone: string,
  pay: string,
) {
  let temp = 'sunil';
  return `
  <div class="tGenie">
   
    <span class="c00">
   <h1 style="color:black; font-family:verdana; text-align:center; font-size:300%;">tGenie - Invoice</h1>
   
   <img src="https://www.w3schools.com/images/w3schools_green.jpg"  alt="Flowers in Chania" style="width:200px;height:200px;">
    <body>
    
   
<table>

<tr>
    <td  scope="row"  align="center" colspan="2"><h1 style="color:black;  font-size:200%;">Name:</h1></td>
    <td  scope="row" align="center" colspan="2"><h1 style="color:black; font-size:200%;">${name}</h1></td>
  </tr>
  <tr>
    <td  scope="row"  align="center" colspan="2"><h1 style="color:black;  font-size:200%;">Email:</h1></td>
    <td  scope="row" align="center" colspan="2"><h1 style="color:black; font-size:200%;">${email}</h1></td>
  </tr>
  <tr>
    <td  scope="row"  align="center" colspan="2"><h1 style="color:black;  font-size:200%;">Phone Num:</h1></td>
    <td  scope="row" align="center" colspan="2"><h1 style="color:black; font-size:200%;">${phone}</h1></td>
  </tr>
  <tr>
    <td  scope="row"  align="center" colspan="2"><h1 style="color:black;  font-size:200%;">Amount Pay:</h1></td>
    <td  scope="row" align="center" colspan="2"><h1 style="color:black; font-size:200%;">${pay}</h1></td>
  </tr>
  
</table>
</body>
        <h1 style="color:black; font-family:verdana; text-align:center; font-size:300%;">Thank you</h1>
  </span>
</div>
`;
}
