### ISSUE TITLE
 Possible Unhandled Promise R TypeError: null is not an object (evaluating '_reactNativeHtmlToPdf.default.convert')  in Android

### ISSUE THREAD

**Issue by lylest** [christopherdro/react-native-html-to-pdf#177]
`   async exportPdf(){
        

      let options = {
      html: '<h1>PDF TEST</h1>',
      fileName: 'test',
      directory: 'o-play',
    };

   let file = await RNHTMLtoPDF.convert(options)
// console.log(file.filePath);
alert(file.filePath);
           
       } //export pdf`

**Comment by Jarchisamira** [comment]
import { NativeModules } from 'react-native';
var file = await NativeModules.RNHTMLtoPDF.convert(options)

**Comment by lucaspiressimao** [comment]
I have the same problem and cannot find solution to it. I already tried the first comment but RNHTMLtoPDF still null. Any ideas ?

**Comment by PabloTeari** [comment]
[IOS] Required "pod install" in the ios project folder. fix for me.
