### ISSUE TITLE
Commit 'Updated from UIWebView to WKWebview' doesn't came in npm install

### ISSUE THREAD

**Issue by matheushchaves** [christopherdro/react-native-html-to-pdf#178]
When I use the npm install in the package, the commit to fix the webkit does not come and when publishing the apple I am complaining with the following message (I saw that only 2 files were changed and I fixed it in the folder, if it is possible to fix, thank you):

Dear Developer,

We identified one or more issues with a recent delivery for your app, "JCA" 0.1 (1). Please correct the following issues, then upload again.

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Best Regards,

The App Store Team

**Comment by AKKIDETROJA** [comment]
same here please update new commit 
Thank you

**Comment by krystianpach** [comment]
+1

**Comment by sage-gu** [comment]
+1

**Comment by christopherdro** [comment]
Update released in v0.9.0
