### ISSUE TITLE
Cannot read property 'convert' of undefined on iOS

### ISSUE THREAD

**Issue by vitolipari** [christopherdro/react-native-html-to-pdf#179]
When I create pdf from ( simple ) HTML string, I get this error:

`Cannot read property 'convert' of undefined`

this is my code
```javascript
import RNHTMLtoPDF from 'react-native-html-to-pdf';
let datab64 = RNHTMLtoPDF.convert({
        html: htmlBuider,
        base64: true
    })
```

**Comment by quangcanh2975** [comment]
I faced the same error then I changed to the latest version (0.8.0) then use command:
`cd ios && pod install`
Hope this help
