### ISSUE TITLE
Firebase storage URL not working on tag IMG SRC

### ISSUE THREAD

**Issue by leoceolin** [christopherdro/react-native-html-to-pdf#181]
I have the code below to insert an image to a PDF

` <div style="height: 550px;">
            <img
              style="width: 500px; height: 550px; margin: 10px;"
              src="https://firebasestorage.googleapis.com/v0/b/alvorecer-7db0e.appspot.com/o/satelite%2Fndvi%2F20200323_T08%20MILHETO.png?alt=media&token=af32571a-f155-4341-87bb-f8e82539d835"
              alt="Imagem NDVI"
            />
          </div>`

but it isn't working with this URL, anyone can help ?

convert to base64 isn't an option because i'll generate many images and then it will generate a huge PDF file

**Comment by leoceolin** [comment]
this PR -> fixed images on Android

solved the problem !

**Comment by asadadams** [comment]
@leoceolin firebase images in storage dont work
