### ISSUE TITLE
No local pictures in PDF's anymore

### ISSUE THREAD

**Issue by JensSam** [christopherdro/react-native-html-to-pdf#182]
Hi, 

Since I updated to the latest version and manually copied the WebKit .h and .m files to my app all locally stored pictures I put in an <IMG> in the PDF are gone. 

Bundled files work fine, but not the one's in e.g. the app's documents directory. So far I've only managed to test on iOS, and the strange thing is that it works perfectly in the Xcode iPhone emulator on my Mac. But if I run it on my iPhone device (I've tried two different iPhones) everything renders into the pdf except from pictures. (still the pictures in the bundle works fine). 

It's really strange and I really can't find anything wrong with my code, especially since it works in the emulator. 

Did anything change with the move from UIWebView that might have disrupted this? 

Thanks!

//Jens

**Comment by GeorgS** [comment]
I am facing the same issue on iOS.

**Comment by uttampawar** [comment]
If I decide to make the change to fix the issue in my local node_modules/react-native-html-to-pdf folder ( android/src/main/java/android/print/PdfConverter.java ) how do I build the java native component?

**Comment by christopherdro** [comment]
Fix release in v0.9.0
