### ISSUE TITLE
crash on android 10

### ISSUE THREAD

**Issue by rusliabdulgani** [christopherdro/react-native-html-to-pdf#185]
Hi all,

Is any update related crash apps in android 10?

**Comment by shadowjade10** [comment]
I had a similar issue, I could create pdfs just fine on api28 but android 10 just crashes, I changed the RNHTMLtoPDF.convert options from what the docs give as an example: 
`  let options = {
    html: html,
    fileName: name,
    directory: 'Documents',
  };`
to: 
`  let options = {
    html: html,
    fileName: name,
  };`
Removing "directory: 'Documents'" defaults to the cache directory.

**Comment by weymanator** [comment]
I faced the same issue, solved by adding this to AndroidManifest

`
<application
    ...
    android:requestLegacyExternalStorage="true"
>`

**Comment by firdaussoberi** [comment]
> I faced the same issue, solved by adding this to AndroidManifest
> 
> ```
> <application
>     ...
>     android:requestLegacyExternalStorage="true"
> >
> ```

@weymanator This helps! Thanks.

**Comment by matheusnrc** [comment]
Ajudou muito!! :) :) :)

![image](https://user-images.githubusercontent.com/24232789/101167988-22bba980-3611-11eb-9752-0389a4501439.png)

**Comment by hoanglehaithanh** [comment]
I had to combine both solutions from @shadowjade10 and @weymanator on Android 10. Thanks all.

**Comment by AwaisIbrar9** [comment]
> I faced the same issue, solved by adding this to AndroidManifest
> 
> ```
> <application
>     ...
>     android:requestLegacyExternalStorage="true"
> >
> ```

Yeah Perfect solution

**Comment by sundardsTechMind** [comment]
Can anyone help me this not able to apply this
<application
    ...
    android:requestLegacyExternalStorage="true"
>

**Comment by weymanator** [comment]
@sundardsTechMind Can you show us what are you trying to do?

**Comment by usman852** [comment]
@weymanator

**Comment by usman852** [comment]
=> let options = {
            html: '<h1>Heading 1</h1><h2>Heading 2</h2><h3>Heading 3</h3>',
            fileName: 'test',
            directory: 'Documents',
           
        };

        try {
            const results = await RNHTMLtoPDF.convert(options)
            console.log(results)
        } catch (err) {
            console.error(err)
        }

=>i also added this in manifiest ..
<application
    ...
    android:requestLegacyExternalStorage="true"
>

app is crashed ..
any solution ? @weymanator

**Comment by usman852** [comment]
My app is crashed 
code here: 
 let options = {
            html: 'test pdf',
            fileName: 'test',
            directory: 'Documents',
           
        };

        try {
            const results = await RNHTMLtoPDF.convert(options)
            console.log(results)
        } catch (err) {
            console.error(err)
        }
i also added this => android:requestLegacyExternalStorage="true"

@weymanator @firdaussoberi @shadowjade10

**Comment by weymanator** [comment]
@usman852 Have you tried the @shadowjade10 solution?

**Comment by Noitham** [comment]
> I faced the same issue, solved by adding this to AndroidManifest
> 
> ```
> <application
>     ...
>     android:requestLegacyExternalStorage="true"
> >
> ```

This solution won't be valid anymore starting 5th of May:

![image](https://user-images.githubusercontent.com/32934478/116538578-ff5b0900-a8e7-11eb-995b-ffd26f25b486.png)

**Comment by deddyprianto** [comment]
i can't find file pdf on /data/user/0/com.absensipdf/cache/absensi3780613586806435873.pdf . please help

**Comment by deddyprianto** [comment]
i try remove property documents on variable options and add this <application
    ...
    android:requestLegacyExternalStorage="true"
> to androidManifest 

i just give feedback path string /data/user/0/com.absensipdf/cache/absensi3780613586806435873.pdf , but i can't find file pdf  on my android

**Comment by Guilherme-Knorst** [comment]
> > I faced the same issue, solved by adding this to AndroidManifest
> > ```
> > <application
> >     ...
> >     android:requestLegacyExternalStorage="true"
> > >
> > ```
> 
> This solution won't be valid anymore starting 5th of May:
> 
> ![image](https://user-images.githubusercontent.com/32934478/116538578-ff5b0900-a8e7-11eb-995b-ffd26f25b486.png)

I had to remove the 'directory' from options to make it work without the android:requestLegacyExternalStorage="true"

**Comment by RaguRam1991** [comment]
> I faced the same issue, solved by adding this to AndroidManifest
> 
> ```
> <application
>     ...
>     android:requestLegacyExternalStorage="true"
> >
> ```

thank you so much, it is worked for me

**Comment by deddyprianto** [comment]
@Guilherme-Knorst where you can find PDF file

**Comment by deddyprianto** [comment]
i just give feedback path string /data/user/0/com.absensipdf/cache/absensi3780613586806435873.pdf , but i can't find file pdf on my android @Guilherme-Knorst

**Comment by altssolution** [comment]
> android:requestLegacyExternalStorage="true"

working, remove the 'directory' from options

**Comment by Salem-Abderaouf** [comment]
@deddyprianto did you find any solution ?
