### ISSUE TITLE
APK Size Almost Doubles

### ISSUE THREAD

**Issue by haresh4d** [christopherdro/react-native-html-to-pdf#186]
After adding this package to my project it has increased the size of apk to double. There are duplicate folders created in apk.

**Comment by marcorm** [comment]
any solution to this?

**Comment by haresh4d** [comment]
You will have to use react-native-print

**Comment by Onibenjo** [comment]
You could use [react-native-html-to-pdf-lite](https://www.npmjs.com/package/react-native-html-to-pdf-lite) which is a lighter  version
