### ISSUE TITLE
A solution to add images to a PDF?

### ISSUE THREAD

**Issue by esutton** [christopherdro/react-native-html-to-pdf#19]
Maybe add to readme if there is a solution.

**Comment by Nicolas-Menettrier** [comment]
https://github.com/christopherdro/react-native-html-to-pdf/issues/3

You can also put the image directly in base64

**Comment by esutton** [comment]
@Nicolas-Menettrier Thanks for tip!

I guess as long as the img src references a locally accessible image I think I should be good.

**Comment by prabakaranrvp** [comment]
@Nicolas-Menettrier using a base64 image data is not working for me. I am developing for Android?
Is it actually working for anyone else?

**Comment by DanielDoe** [comment]
Using base64 doesn't work for me either any help?
