### ISSUE TITLE
RNHTMLtoPDF.convert(options) don't return nothing.

### ISSUE THREAD

**Issue by jochercoles** [christopherdro/react-native-html-to-pdf#194]
Hello dears. I have the following code, where I create a number of important pages, about 200 pages. Until a few days ago it worked fine, and without problems, but from one moment to another, the PDF file is not being created. I don't know what could have changed. Is it possible that you can help me? I ask for the corresponding permissions to write to the Android Download folder, but it doesn't work.

From already thank you very much.

Javier.

    async createPDF(data) {
      try
      {
        var headerHTML = '<html>' +
                            '<head>' +
                              '<style>table {width: 100%;} table, td {text-align: center; font-family: Arial, Helvetica, sans-serif;}</style>' +
                            '</head>' +
                          '<body>';
        var footerHTML = '</body>' +
                         '</html>';

        var bodyHTML = ''

        const { allBranchs, selectedOperativeModelId } = this.state;
        let operativeModelId = "0".repeat(3 - selectedOperativeModelId.length) + selectedOperativeModelId.toString();

        // Crear archivo PDF con cada una las etiquetas o marbertes de colectora.
        data.forEach(collectorLabel => {
          let collectorNumber = "0".repeat(6 - collectorLabel.colectora.length) + collectorLabel.colectora.toString();
          let assignCollectorCode = "ASIGNA" + collectorNumber;
          let unassignCollectorCode = "DESASI" + collectorNumber;
          let transferBetweenCollectorsCode= "TRASNF" + collectorNumber;
          let closeCollectorCode = "CIERRE" + collectorNumber;
          let isSortable = collectorLabel.sorteable === "True" ? "SI" : "NO";
          let isKeeping = collectorLabel.custodia === "True" ? "SI" : (collectorLabel.custodia === undefined || collectorLabel.custodia === null) ? "" : "NO";
          let multiDestination = collectorLabel.multiDestino === "True" ? " (Multi Destino)" : "";
          let sucursalDescription = (collectorLabel.sucursal === undefined || collectorLabel.sucursal === null) ? "" : collectorLabel.sucursal.toUpperCase();

          bodyHTML += '<table style="page-break-after: always;">' +
                        '<tr>' + 
                          '<td colspan="2" style="color: green; font-size: 50; font-weight: bold;">ASIGNA</td>' +
                          '<td colspan="2" rowspan="2" style="color: grey; font-size: 120; font-weight: bold; text-align: center;">' + 
                            "0".repeat(3 - collectorLabel.idSucursal.length) + collectorLabel.idSucursal.toString() + '</td>' +
                          '<td style="color: red; font-size: 50; font-weight: bold;">DESASIGNA</td>' + 
                        '</tr>' +
                        '<tr>' +
                          '<td colspan="2" style="color: green;">' +
                            '<svg id="barcodeAsigna">' + this.update(assignCollectorCode, '', '', 'black') + '</svg>' +
                          '</td>' +
                          '<td style="color: red;">' + 
                            '<svg id="barcodeDesasigna">' + this.update(unassignCollectorCode, '', '', 'black') + '</svg>' +
                          '</td>' +
                        '</tr>' +
                        '<tr height="150">' +
                          '<td colspan="5" style="color: grey; font-size: 70; font-weight: bold; text-align: center; vertical-align: top;">' + sucursalDescription + multiDestination + '<td>' +
                        '</tr>' + 
                        '<tr>' +
                          '<td style="color: grey; font-size: 30;">Sorter</td><td style="color: grey; font-size: 30;">Custodia</td>' + 
                          '<td style="color: grey; font-size: 30;">Modelo</td>' +
                          '<td style="color: grey; font-size: 30;">Rampa</td>' +
                          '<td style="color: grey; font-size: 30;">Colectora</td></tr>' +
                        '<tr>' +
                          '<td style="color: grey; font-size: 40;">' + isSortable + '</td>' +
                          '<td style="color: grey; font-size: 40;">' + isKeeping + '</td>' +
                          '<td style="color: grey; font-size: 70; font-weight: bold;">' + "0".repeat(3 - collectorLabel.idModeloOperativo.length) + collectorLabel.idModeloOperativo.toString() + '</td>' + 
                          '<td style="color: grey; font-size: 70; font-weight: bold;">' + "0".repeat(3 - collectorLabel.rampa.length) + collectorLabel.rampa.toString() + '</td>' +
                          '<td style="color: grey; font-size: 70; font-weight: bold;">' + collectorLabel.colectora + '</td>' +
                        '</tr>' +
                        '<tr>' +
                          '<td colspan="2" rowspan="3" style="color: blue;">' +
                            '<svg id="barcodeTransfer">' + this.update(transferBetweenCollectorsCode, '', '', 'black') + '</svg>' +
                          '</td>' +
                          '<td style="color: grey; font-size: 15; font-weight: bold; text-align: left; padding-left: 30; height: 40px;">Planta Operativa:</td>' +
                          '<td style="color: grey; font-size: 15; text-align: left; padding-left: 10; height: 40px;">' + collectorLabel.plantaOperativa + '</td>' +
                          '<td colspan="2" rowspan="3" style="color: orange">' +
                            '<svg id="barcodeCierre">' + this.update(closeCollectorCode, '', '', 'black') + '</svg>' +
                          '</td>' +
                        '</tr>' +
                        '<tr>' + 
                          '<td style="color: grey; font-size: 15; font-weight: bold; text-align: left; padding-left: 30; height: 40px;">Unidad de Trabajo:</td>' +
                          '<td style="color: grey; font-size: 15; text-align: left; padding-left: 10; height: 40px;">' + collectorLabel.unidadTrabajo + '</td>' + 
                        '</tr>' +
                        '<tr>' +
                          '<td style="color: grey; font-size: 15; font-weight: bold; text-align: left; padding-left: 30; height: 40px;">Modelo Operativo:</td>' +
                          '<td style="color: grey; font-size: 15; text-align: left; padding-left: 10; height: 40px;">' + collectorLabel.modeloOperativo + '</td>' +
                        '</tr>' +
                        '<tr>' +
                          '<td colspan="2" style="color: blue; font-size: 50; font-weight: bold;">TRANSFIERE</td>' +
                          '<td style="color: grey; font-size: 15; font-weight: bold; text-align: left; padding-left: 30; height: 40px;">Sector Operativo:</td>' +
                          '<td style="color: grey; font-size: 15; text-align: left; padding-left: 10; height: 40px;">' + collectorLabel.sectorOperativo + '</td>' + 
                          '<td style="color: orange; font-size: 50; font-weight: bold;">CIERRE</td>' +
                        '</tr>' +
                      '</table>';
        });    

        let dateTime = new Date();
        let creationDate = dateTime.getFullYear() + 
                           (dateTime.getMonth() < 10 ? '0' + dateTime.getMonth() : dateTime.getMonth()) +
                           (dateTime.getDate() < 10 ? '0' + dateTime.getDate() : dateTime.getDate()) + '_' +
                            dateTime.getHours() + dateTime.getMinutes() + dateTime.getSeconds();
        let fileName = 'marbetes_' + creationDate;

        let options = { 
                html: headerHTML + bodyHTML + footerHTML,
                fileName: fileName,
                directory: 'Download',
                height: 612,
                width: 792
        };

        **let file = await RNHTMLtoPDF.convert(options);
        
        await RNPrint.print({ filePath: file.filePath, isLandscape: true });**
    }
    catch (err)
    {
        console.error(656, err);
    }
  }

**Comment by Noitham** [comment]
Did you bump the `targetSDK` version (29) on the `build.gradle` file?
