### ISSUE TITLE
No encuentro el archivo PDF en el Iphone

### ISSUE THREAD

**Issue by JPierre1997** [christopherdro/react-native-html-to-pdf#197]
se ha implementado la libreria correctamente , en el simulador si se esta creando un archivo pdf , pero al momento de probar la app en un dispositivo real, no encuentro el archivo pdf que se genera

**Comment by christopherdro** [comment]
The asset uri might differ between sim and a real device. Can you provide an example of how you are using the returned asset uri after conversion?
