### ISSUE TITLE
Empty PDF after bumping to targetSDK 29

### ISSUE THREAD

**Issue by Noitham** [christopherdro/react-native-html-to-pdf#198]
As described on the title, one of the things we've noticed so after bumping the `targetSDK` version of our app to SDK 29, is that it isn't possible for us to generate a PDF using the RNHTMtoPDF library.

Has anyone else experienced this issue?

PDF file gets created on the given route wit the given`fileName`, but its content is empty.

**Comment by hanaechahid** [comment]
hello @Noitham, I have the same issue yesterday I changed the targetsdk from 28 to 29, after this change I got just an empty pdf no data appears. Did you find any solution for that? 
@christopherdro could you please take a look on this issue?

**Comment by Noitham** [comment]
> hello @Noitham, I have the same issue yesterday I changed the targetsdk from 28 to 29, after this change I got just an empty pdf no data appears. Did you find any solution for that?
> @christopherdro could you please take a look on this issue?

Hey @hanaechahid, upgrading to react-native 0.63.3 made it work again on our case :)

**Comment by hanaechahid** [comment]
first thank you @Noitham ,  but I can't upgrade react native to this version at the moment, is there any other solution please?

**Comment by Noitham** [comment]
> first thank you @Noitham , but I can't upgrade react native to this version at the moment, is there any other solution please?

Disregard my latest answer, upgrading react-native to 0.63.3 didn't solve the issue.

**Comment by ThibaultG1** [comment]
I've just also experienced the same issue after bumping from targetSDK 28 to 29.

**Comment by gundlev** [comment]
It seems that a fix for this problem have already been made in 3 seperat pull requests:

https://github.com/christopherdro/react-native-html-to-pdf/pull/195
https://github.com/christopherdro/react-native-html-to-pdf/pull/169
https://github.com/christopherdro/react-native-html-to-pdf/pull/108

Forking the repo and adding the fix worked for us. Not sure why none of the pr's have been merged yet.

**Comment by ThibaultG1** [comment]
Thanks for the idea! It worked.

**Comment by hanaechahid** [comment]
hello, how did you solved the issue?

**Comment by ThibaultG1** [comment]
Hello,
As @gundlev said, by forking the repo and copying the fix.

`mWebView.loadData(mHtmlString, "text/HTML; charset=utf-8", null);`
should be replaced by:
`mWebView.loadDataWithBaseURL(mBaseURL, mHtmlString, "text/HTML", "utf-8", null);`
in `android/src/main/java/android/print/PdfConverter.java`.

then replace the `react-native-html-to-pdf`dependency in the project with your fork.
e.g: `npm uninstall react-native-html-to-pdf && npm install git+https://github.com/ThibaultG1/react-native-html-to-pdf`

**Comment by gabrielhdgb** [comment]
Don't work for me, have other solution? :(

**Comment by Joralmo** [comment]
I did the fork and it worked correctly, when testing in debug mode the images are displayed in the pdf but when installing the apk release the images are not displayed, has something similar happened to anyone?

**Comment by christopherdro** [comment]
Changes linked in this comment https://github.com/christopherdro/react-native-html-to-pdf/issues/198#issuecomment-725485209 have been merged and released on v0.9.0

**Comment by liamjones** [comment]
FYI, while v0.9.0 contains the fix for API level 29 it will also try to move your rootProject to API 28. Took me a while to track down since it resulted in a different module seeing SDK 28 rather than 29. I've raised a PR to resolve this: https://github.com/christopherdro/react-native-html-to-pdf/pull/203

**Comment by christopherdro** [comment]
@liamjones Thanks. I'll release a patch for v0.9 with your changes.

**Comment by dayachand-systematix** [comment]
Uninstall the package "npm uninstall react-native-html-to-pdf" and reinstall again "npm install react-native-html-to-pdf".

**Comment by liamjones** [comment]
@christopherdro does this need closing now? v0.9.1 is working fine for us on SDK 29 now.

**Comment by Arshimonde** [comment]
just update the package to the current version

**Comment by aliMurtaja** [comment]
thanks @gundlev its works for me, I spent lot of time to solve this
