### ISSUE TITLE
Why can't I change the fileName and directory - Android

### ISSUE THREAD

**Issue by johnbryant** [christopherdro/react-native-html-to-pdf#20]
I need to save the pdf file in my own directory, but no matter how I change the directory and fileName, the file is saved to '/Documents/MyPdf.pdf', What can I do?!

**Comment by Nicolas-Menettrier** [comment]
Can you post you're code please ? You can't change the directory, you have only the choice between temp and Documents directory

**Comment by esutton** [comment]
On Android, the file name is hard-coded to **MyPdf.pdf**

I do not understand why.

https://github.com/christopherdro/react-native-html-to-pdf/blob/master/android/src/main/java/com/parkerdan/htmltopdf/RNHTMLtoPDFModule.java#L62

**Comment by christopherdro** [comment]
Support added in v0.3.0
https://github.com/christopherdro/react-native-html-to-pdf/releases/tag/v0.3.0
