### ISSUE TITLE
How to Remove padding??

### ISSUE THREAD

**Issue by viveKing21** [christopherdro/react-native-html-to-pdf#201]
everything works perfectly
but i have a background image, and its really working perfectly but im getting padding in generated pdf , thats not i want, How can i remove this? any solution?
I'm using Android!

**Comment by christopherdro** [comment]
Can you try setting padding and margins on `body` and `html` to 0?

**Comment by tioluwani94** [comment]
Hi @christopherdro, setting padding and margins on the `body` and `html` to 0 doesn't remove the spacing. I using Android as well. Any other suggestions that might help?

**Comment by bboniin** [comment]
> Olá , @christopherdro , definir o preenchimento e as margens em `body`e `html`como 0 não remove o espaçamento. Também estou usando o Android. Alguma outra sugestão que possa ajudar?

Conseguiu algo amigo??

**Comment by HodayaGruz** [comment]
@christopherdro hi, i got this bug too, there is a way to fix it? i need it as fast as you can.
tnxxxxx

**Comment by HodayaGruz** [comment]
https://stackoverflow.com/questions/48261430/where-do-these-margins-come-from
this solve my problem, but i think its something that should be by default some how.

**Comment by Talha-Jawed** [comment]
i found it, write this code:

html : '<style> @page{ background-color: red; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; margin-bottom: 0pt; padding-left: 0pt; padding-right: 0pt; padding-top: 0pt; padding-bottom: 0pt; } </style>'

adjust the values as you want.

**Comment by AmdjedSanero** [comment]
> i found it, write this code:
> 
> html : '<style> @page{ background-color: red; margin-left: 0pt; margin-right: 0pt; margin-top: 0pt; margin-bottom: 0pt; padding-left: 0pt; padding-right: 0pt; padding-top: 0pt; padding-bottom: 0pt; } </style>'
> 
> adjust the values as you want.

thank you its working
