### ISSUE TITLE
Cannot read property 'convert' of undefined on web platform

### ISSUE THREAD

**Issue by EricRajoelison** [christopherdro/react-native-html-to-pdf#204]
When I build the application on web platform, it shows me : 
`Unhandled Rejection (TypeError): Cannot read property 'convert' of undefined`

Although, on Android it works perfectly.
Here is my code: 
 ```
let options = {
        html: createHTML(),
        fileName: 'test',
        directory: 'Documents',
    };

    let file = await RNHTMLtoPDF.convert(options)
     alert(file.filePath);
```

Any idea?
Thank you in advance.

**Comment by melero2000** [comment]
Same error here. Did you get it fixed? @EricRajoelison

**Comment by melero2000** [comment]
> Same error here. Did you get it fixed? @EricRajoelison

Use --save when installing it. This is how it worked for me
