### ISSUE TITLE
Headers not repeating in IOS

### ISSUE THREAD

**Issue by nikitpanchal** [christopherdro/react-native-html-to-pdf#206]
Hello Chris @christopherdro 
Could you help me with following problem i'm facing
I have a Prescription contains header and that Prescription later gets divide in to multiple pages depend on the Height of the HTML.
Now in Android the header gets repeated on each pages, but the same HTML when converted to pdf in IOS header binds on only first page. 
What could be the issue? Is that IOS do not have capability to understand THEAD element 
Bellow Screen shot attached  PDF converting using [HTML ](https://rx.prescrip.in/template/report.html?patientid=602363aa88499f0db0cbba89):
**Android Header repeats**
<a href="https://ibb.co/DgQ8gfr"><img src="https://i.ibb.co/k6X962m/9b48c128-c3c8-4f63-8143-da65933d3aef.jpg" alt="9b48c128-c3c8-4f63-8143-da65933d3aef" border="0"></a>

**IOS No repeat**
<a href="https://ibb.co/6XG8ZYf"><img src="https://i.ibb.co/Z2vSJdk/35de001f-f92e-425c-a2a6-e2368ac79c73.jpg" alt="35de001f-f92e-425c-a2a6-e2368ac79c73" border="0"></a><br /><a target='_blank' href='https://dedupelist.com/'>remove duplicates from list online</a><br />

**Comment by Tarunpreetsingh16** [comment]
Hi, can you tell me how did you repeat the header part on android?

**Comment by genocideaon** [comment]
I am facing this issue and I cannot count table rows to create a new table because text length problem. Please, suggest a solution.

**Comment by genocideaon** [comment]
> Hi, can you tell me how did you repeat the header part on android?

It repeats itself for Android

**Comment by rushg171** [comment]
Hi @nikitpanchal @sungsong88 @genocideaon @Tarunpreetsingh16  my headers & footers are overlapping the content. How were you able to solve it?
PDF: https://ibb.co/w71KmXq
I tried adding margins but no luck.
Any help is appreciated. Thank you!
