### ISSUE TITLE
Working fine in emulator but crash when run same in Actual device

### ISSUE THREAD

**Issue by pratikjain36** [christopherdro/react-native-html-to-pdf#207]
Working fine in emulator but crash when run same in Actual device.

**Comment by pratikjain36** [comment]
After updating the \android\app\src\main\AndroidManifest.xml path it worked fine.
https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android/57804657#57804657

**Comment by amalmohann** [comment]
go to AndroidManifest.xml file and add android:requestLegacyExternalStorage="true" in <Application>
