### ISSUE TITLE
Using # in the HTML creates PDF in blank

### ISSUE THREAD

**Issue by SentenciaSQL** [christopherdro/react-native-html-to-pdf#208]
Using the character # at any point of the HTML makes the PDF to be in blank, is any workaround for this?

**Comment by balwinders** [comment]
I faced the same issue and couldn't find any workaround. I had to remove the # character from HTML. Though this happened on the Android Platform only. The iOS seems to be working fine with the # character.

**Comment by sundardsTechMind** [comment]
I'm also facing PDF Blank issue if  I use Android API Level 28 it's working fine if i upgrade to API Level 29 it's getting failed 
Issue: Bank Page & App crash
Please help me if any update 

Thanks in advance

**Comment by sundardsTechMind** [comment]
Fixed this issue It's only coming for android 10 API Level 29
Add this Design  For PDF
      paddingLeft: 10,
      paddingRight:10,
      paddingTop:10,
      paddingBottom:10,
      padding:10,

**Comment by tanoto-the-explorer** [comment]
@sundardsTechMind your solution doesn't work in mine, can I see the options you add on the RNHTMLtoPDF.convert({options}) if that's okay? Thanks :)

**Comment by iamrohitagg** [comment]
Did anyone get any solution for this problem? I am facing this issue on RN 0.64+ but it works fine in 0.60.
