### ISSUE TITLE
How to store the generated pdf on iPhone

### ISSUE THREAD

**Issue by vinutam** [christopherdro/react-native-html-to-pdf#209]
The pdf generated using react-native-html-to-pdf will be saved in the Documents folder of Android, but for iOS I'm not able to get where exactly it is stored on iPhone. The filePath says /var/mobile/Containers/Data/Application/XXXX/Library/Documents/test.pdf, but I want that to be stored in iPhone's Files App.
How to do it?

**Comment by Talha-Jawed** [comment]
same issue in iOS , any luck how i resolve this issue?

**Comment by puneetkansal04** [comment]
Please provide solution for this,

**Comment by prolok** [comment]
Technically "Files App" is another app, and iOS would not allow you directly access the storage of any other applications, hence I believe you cannot save any file directly to the Files app from your own app.

You can only pass the file to Files app via the Share function, thus I don't think it is what you guys want...
