### ISSUE TITLE
No local images in PDF on iOS 

### ISSUE THREAD

**Issue by Reppik** [christopherdro/react-native-html-to-pdf#210]
Hi, 
i have the Version 0.9.1 of react-native-html-to-pdf. On the iOS simulator works everything fine. But on the real device it doesn't show any local images. 
Anyone with a suggestion?

Thanks 

Best regards
Eduard

**Comment by Reppik** [comment]
I solved the issue by using base64 encoding, instead of using the local path.

**Comment by Talha-Jawed** [comment]
@Reppik can you help me? how to create image into html?

**Comment by Reppik** [comment]
@Talha-Jawed where exactly have you problems? 
The problem i had was solved by using this codeline: 
`<img src="**data:image/png;base64,**${carImage}" width="285" height="180"/>`.
Hope i could help you.

**Comment by dimatretyak** [comment]
> I solved the issue by using base64 encoding, instead of using the local path.

@Reppik thank you for sharing this information! I had the same problem, but I solved it by converting local images to base64
