### ISSUE TITLE
Allow custom page size

### ISSUE THREAD

**Issue by davwheat** [christopherdro/react-native-html-to-pdf#211]
In the UK, we use A paper sizes, most commonly A4.

Some device and printer combos default to A3 (about 2x US Letter or exactly 2x A4) because Letter is slightly wider than A4.

Having the option to select a custom paper size (e.g. A4) would be **very** helpful.

**Comment by christopherdro** [comment]
See documentation here: https://github.com/christopherdro/react-native-html-to-pdf#options

You can use point values to set `height` and `width`

Reference to paper sizes: https://www.prepressure.com/library/paper-size
