### ISSUE TITLE
Windows support!

### ISSUE THREAD

**Issue by Omar-Belghaouti** [christopherdro/react-native-html-to-pdf#214]
This package is very helpful and need to be implemented for Windows platform.

**Comment by Omar-Belghaouti** [comment]
@christopherdro is there any news on this?

**Comment by Qurishe** [comment]
Hi, anything about the windows support or an alternative way for RNW to generate pdfs?

**Comment by Omar-Belghaouti** [comment]
> Hi, anything about the windows support or an alternative way for RNW to generate pdfs?

you can check this https://github.com/microsoft/react-native-windows/issues/7723#issuecomment-856814235

**Comment by Qurishe** [comment]
Thank u Omar, what i didn't get is "user's Path as an environment variable" and the second one is which c# file do i have to add it to?

**Comment by christopherdro** [comment]
@anupriya13 @TatianaKapos Any ideas on the LOE to add windows support for this package? This is often used with react-native-print.

**Comment by raorugan** [comment]
Hello @christopherdro  - can you clarify you need it for new architecture (Fabric) in Windows? Also which version of RNW and which architecture are you using?

**Comment by christopherdro** [comment]
@raorugan I'll be only supporting the new architecture moving forward.

**Comment by christopherdro** [comment]
@raorugan I just recently updated his library to support the new architecture will only be maintaining that moving forward. There's currently no support for windows.
