### ISSUE TITLE
Page breaks?

### ISSUE THREAD

**Issue by gburnett** [christopherdro/react-native-html-to-pdf#215]
How does this library determine when to make a page break?

I've been trying it out and I find that elements can span two separate pages. Like this:

![pageBreak](https://user-images.githubusercontent.com/1595464/115021739-44c51280-9eb4-11eb-85e8-3d00b6dcf50a.png)

The structure of this example is very simple:

``` html
<html>
  <head></head>
  <body>
    <section style="border:solid 1px black;"><p>item</p></section>
    <!-- sections repeat n times -->
  </body>
</html>
```

**Comment by GlobusHugoSchmitt** [comment]
One can force a page break using this solution https://stackoverflow.com/questions/1664049/can-i-force-a-page-break-in-html-printing
That doesn't help my issue, though. I want to add heading to all pages.

**Comment by aclowkey** [comment]
Any ideas how to overcome this?
