### ISSUE TITLE
RNHTMLtoPDF.convert() stuck!

### ISSUE THREAD

**Issue by yesbrad** [christopherdro/react-native-html-to-pdf#217]
Hi!

This plugin has been live in my client's app now for 10 months now and about 1 month ago I started getting complaints about the main feature not working. Which uses this package to print off a Retail Sales Ticket. The app is Android Only at the moment.

What been happening is when it hits RNHTMLtoPDF.convert() it's just hangs. I must note it will work maybe one or two times before it hangs. This never used to happen ever. I assume maybe an Android Update has messed something up.

I'm not doing anything crazy with my HTML and I am using Convert with async/await. I've looked over the logcat and nothing out of the ordinary is coming up.

If anyone has shed any light, please. I'm desperate.

**Comment by yesbrad** [comment]
6 hours of banging my head against a wall and I've found that the PDF isn't made correctly and gets corrupted. Then when you go to override the corrupt file it hangs.

**Comment by sundardsTechMind** [comment]
Update your android API level 29 and check again it will work.

**Comment by shubhamdeol** [comment]
https://github.com/christopherdro/react-native-html-to-pdf/pull/226

I have raised a pr to fix this issue here
