### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by noushad-techconfer** [christopherdro/react-native-html-to-pdf#223]
When Reset the app Its Crash on path directory: 'Documents',
after some times it work's
when I remove's directory: 'Documents' 
pdf are store in local cache but unable to find it

**Comment by RaguRam1991** [comment]
if it is android 10? try this https://github.com/christopherdro/react-native-html-to-pdf/issues/185#issuecomment-701631047

seems this issue closed.
