### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by melaniebrgr** [christopherdro/react-native-html-to-pdf#225]
I am regularly required to compile the licenses disclaimers for the dependencies of the application I'm working on. We recently added `react-native-html-to-pdf` as a project dependency (thank you :). When I ran `yarn licenses generate-disclaimer` I noticed it was missing from the output, and then that this file was missing from the repository. For example, see https://github.com/facebook/react/blob/master/LICENSE for instance. Thanks!

**Comment by christopherdro** [comment]
Thanks for the heads up. License added.
