### ISSUE TITLE
example

### ISSUE THREAD

**Issue by cheufte** [christopherdro/react-native-html-to-pdf#23]
Hi Chris,
could you publish a running example? I am not able to view the created PDF.
I have published on Stackoverflow an example that I run (http://stackoverflow.com/questions/41449747/trying-to-generate-a-pdf-and-view-or-email-it-with-react-native/41700362#41700362) , it seems to create the pdf, but I don't know how to view it in order to mail it later.

Many thanks,
Cheufte

**Comment by christopherdro** [comment]
There is an example project on the repo that supports both iOS and Android on the latest version of react native.

You get the filepath back after the pdf is created and use that to view it or email it.

**Comment by christopherdro** [comment]
In the past i've used this library with success. https://github.com/chirag04/react-native-mail#example

Provide the path that is returned from this library to the `path` key in the attachment options.
