### ISSUE TITLE
font size in rem or cm renders differently on iPad pro and iPhone

### ISSUE THREAD

**Issue by euZebe** [christopherdro/react-native-html-to-pdf#230]
Hi,

Here is a PDF which renders differently according to wheter it is generated from an iPad pro or an iPhone :

![html-to-pdf render issue](https://user-images.githubusercontent.com/9463809/127316509-17022381-1574-413a-97fa-81555f6900c4.png)

Here the HTML source
```
<html>
<style>
  html {
    font-family: Arial;
    font-size: .3cm; 
  }
</style>
<body>
<h1>A title</h1>
<p>A paragraph which should be on a single row, considering the number of characters in it. But as you can see, it's too long on iPad Pro.</p>
</body>
</html>
```

Express the default font size in cm or px does not change anything.

How could I get the exact same rendering, regardless of the device from which it is generated?

**Comment by vimalswaroopj** [comment]
Are you able to use script tag for js  in this?

**Comment by EEimer** [comment]
Same problem here. 
iPad gets the same result with about 30% small font size.
