### ISSUE TITLE
Minimum platform os version

### ISSUE THREAD

**Issue by priyesh9875** [christopherdro/react-native-html-to-pdf#24]
What's the minimum android and iOS version?

I tried running it in android 4.2, and throws no module found error. But working perfectly on android 5+

**Comment by pengfeiyan** [comment]
I tested in Genymotion.It works in android 4.4.4/5.0/6.0/7.0 
In android 4.3. the error message is "Could not invoke RNHTMLtoPDF.convert
![error](https://cloud.githubusercontent.com/assets/24911989/24338605/a36c898e-12e1-11e7-852f-b40e6c020ecc.png)
"

**Comment by christopherdro** [comment]
Should work fine with React Native's minimum support.
https://github.com/facebook/react-native/commit/e2841c05b4bc67aad90854c7013b278ca4abe03a#diff-04c6e90faac2675aa89e2176d2eec7d8R5

Android uses [itextpdf](https://github.com/itext/itextpdf/releases) which might not support older versions.
