### ISSUE TITLE
PDFBox-Android 1.8.10.0 no longer supported

### ISSUE THREAD

**Issue by joshuajameshunt** [christopherdro/react-native-html-to-pdf#240]
PDFBox-Android is now on version 2.0.4.0. The earliest supported versions on Maven or Jitpack are 1.8.10.3 and 2.0.1.0 respectively. This is causing Android builds to fail.

**Comment by joshuajameshunt** [comment]
@christopherdro PDFBox-Android will need to be updated since neither Maven nor Jitpack support 1.8.10.0. See above for current and minimum supported versions.

**Comment by christopherdro** [comment]
It looks like it is supported but there was a small change to the name of the package. https://search.maven.org/artifact/com.tom-roush/pdfbox-android/1.8.10.3/aar
