### ISSUE TITLE
How I can add Images in footer and header of all pdf page that was build using HTML.

### ISSUE THREAD

**Issue by UsmanAhsanPs19** [christopherdro/react-native-html-to-pdf#248]
This means I have an HTML form pdf is creating but now I want to add branding of my customer on each page like adding a brand image in header and footer of all pages. Please guide thanks.

**Comment by sundardsTechMind** [comment]
@UsmanAhsanPs19  try this in your pdf template 
I'm able to add Images Like given below

<div style="margin-bottom: 20pt">
     <img src="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwallpapersafari.com%2Fw%2FmrL0la&psig=AOvVaw20R-UjJO7BXh0_GsnOYpcO&ust=1638521659251000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCOCqtoXfxPQCFQAAAAAdAAAAABAD" style="height: 40pt;"/>
  </div>

**Comment by christopherdro** [comment]
Possibly related to https://github.com/christopherdro/react-native-html-to-pdf/issues/206 ?

**Comment by UzairSamad** [comment]
Any solution for the above scenario i am also got stuck in adding images to pdf

**Comment by KarolHarumi** [comment]
I've made it works but I had to host the image somewhere else. 

Trying to get the image from the relative path didn't work.

**Comment by TechSaq** [comment]
> I've made it works but I had to host the image somewhere else.
> 
> Trying to get the image from the relative path didn't work.

That's the one way and sometimes it can give CORS issue. Just in case someone needs another solution. 

The other solution is to convert the image into base64 data either from the relative path or from hosted URL.
