### ISSUE TITLE
Doesn't work for html5 in android

### ISSUE THREAD

**Issue by nhayfield** [christopherdro/react-native-html-to-pdf#25]
itext will error with: 
com.itextpdf.tool.xml.exceptions.RuntimeWorkerException: Invalid nested tag head found, expected closing tag meta.
Error: com.itextpdf.tool.xml.exceptions.RuntimeWorkerException: Invalid nested tag head found, expected closing tag meta.

or other similar error. need to use a different pdf generator on android or else convert html5 to xhtml

**Comment by nhayfield** [comment]
@christopherdro seeing if i can add jtidy to convert html5 to xhtml before it goes into itext. 
my java skills are pretty rusty though. having trouble importing jtidy to project. will try more tomorrow.

**Comment by nhayfield** [comment]
@christopherdro hmm so i tried adding jtidy and it seemed sort of buggy. i found a solution using your react-native-print library though. you can just print from html string in android.

**Comment by KjellConnelly** [comment]
@nhayfield @christopherdro I see the same bug... html5 looks good on iOS, but it comes out looking all wacky on Android. I need the ability to generate a PDF, so going straight to printing isn't an option for me. Any solutions to this?

**Comment by nhayfield** [comment]
@KjellConnelly sorry i haven't found anything as of yet

**Comment by esutton** [comment]
This fork removed all iText dependencies and HTML to PDF works great on Android.

https://github.com/blink22/react-native-html-to-pdf

* ````<img />```` works with base64 and local files
    * Make sure you close the <img /> tag !
* ````<svg/ >```` renders ( Hint: Reuse [SVG code from Google Material Icons](https://material.io/icons/) )
* CSS style works great.
* Control page breaks from your HTML.
````
<p style="page-break-before: always;" />
````
