### ISSUE TITLE
react-native-html-to-pdf does not work on devices of other brands, other than samsumg

### ISSUE THREAD

**Issue by guibsonmoura** [christopherdro/react-native-html-to-pdf#250]
I have a react-native application that uses the react-native-html-to-pdf library, when I try to generate a pdf on a device of the samsumg brand it works normally, but when I try to generate the pdf on a device of another brand, the even is not generated, can someone tell me why this happens?

**Comment by rohitatcoffee** [comment]
I too had the same issue, I fixed the issue by changing the Gradle(app) compileSdkVersion from 30 to 29 and targetSdkVersion from 30 to 29.

This fixed the issue for me

**Comment by christopherdro** [comment]
Can you provide any more info on the different brand(s) you tried? Crash reports would be helpful for debugging if you can provide them.
