### ISSUE TITLE
Add improvements for Android support

### ISSUE THREAD

**Issue by esutton** [christopherdro/react-native-html-to-pdf#26]
Could these improvements for Android support be merged into this project?

https://github.com/semiautomatix/react-native-html-to-pdf

**Comment by KjellConnelly** [comment]
If this fixes HTML5 not rending properly on android, I would love that :)

**Comment by christopherdro** [comment]
More than happy to accept improvements.

Are there any in particular worth mentioning?

**Comment by KjellConnelly** [comment]
Idk if this is fully fixed or not, but at least I'm finally getting a consistent result on iOS and Android. It's probably getting rid of iText that fixed this. You may be able to close this issue and the previous one about Android looking weird. (just upgraded from 0.3 to 0.6 I think)

**Comment by esutton** [comment]
Closing.  Removing iText was just so awesome!

I can run Android and iOS sided by side in simulators and the PDF reports look practically identical!
