### ISSUE TITLE
Vertical padding on each page

### ISSUE THREAD

**Issue by sidorchukandrew** [christopherdro/react-native-html-to-pdf#260]
I've been trying to figure out how to apply vertical padding/margins to each page of a PDF. The PDF can have an arbitrary number of pages because it is based off user input so I can't just break up the content into separate divs and apply the padding. Are there any settings I'm not aware of for apply padding to internal pages?

![1C89D32C-01AB-41AF-B7AE-CAEF0C980EE1](https://user-images.githubusercontent.com/36050911/151706584-49204ec5-4e4d-43c7-ab80-536adac93b64.jpeg)

**Comment by CaioQuirinoMedeiros** [comment]
@sidorchukandrew have you found a solution?
