### ISSUE TITLE
Path is showing but pdf is not generated

### ISSUE THREAD

**Issue by Nitekurs** [christopherdro/react-native-html-to-pdf#266]
This path is showing " /storage/emulated/0/Android/data/com.reactnative/files/Documents/test.pdf " but pdf not generated

**Comment by Basir-PD** [comment]
1+

**Comment by Antonin-Keuck** [comment]
Did you find a solution or another library to convert html to pdf ?

**Comment by JohnBonesOrtega** [comment]
Same issue here, this happens only on android devices.

**Comment by JeetMistry2812** [comment]
Did anyone find any solution still having the same issue?

**Comment by tahir-jamil** [comment]
how to fix this path issue?
"/storage/emulated/0/Android/data/com.hakeem/files/storage/emulated/0/Download/test.pdf"
