### ISSUE TITLE
Cannot read properties of undefined (reading 'convert')

### ISSUE THREAD

**Issue by namikarif** [christopherdro/react-native-html-to-pdf#271]
`import RNHTMLtoPDF from 'react-native-html-to-pdf';`

`async createPDF(html) {
        let options = {
            html: html,
            fileName: 'test',
            directory: 'Documents',
        };

        let file = await RNHTMLtoPDF.convert(options)
        console.log('filePath : ', file.filePath);
        // alert(file.filePath);
    }`

**Comment by Raheel1258** [comment]
Linking issue. Run this commmand:
`react-native link react-native-html-to-pdf`
