### ISSUE TITLE
I can't add header and footer of  PDF export foreach page in iOS (all versions), in android worked well

### ISSUE THREAD

**Issue by hoyen2608** [christopherdro/react-native-html-to-pdf#272]
I used same code for android and iOS to add header and footer in PDF export multiple pages. In android it worked well, but in iOS, it only displays header in the first page and footer in the last page. Header and footer are midle pages don't display. Please help me.

**Comment by avaiyakapil** [comment]
i also found the same problem footer is working in android but it's not showing in ios while giving position to absolute to footer works !

**Comment by ZGBX** [comment]
I've encountered the same issue; have you guys resolved it?
