### ISSUE TITLE
Urdu Text not getting displayed

### ISSUE THREAD

**Issue by haroon97** [christopherdro/react-native-html-to-pdf#276]
I'm using the react-native-html-to-pdf package. The pdf works fine in English language but when I change my language to any other language except English then the text is not visible and it shows empty spaces instead of the text.

**Comment by haroon-cb** [comment]
This is happening on Android.

**Comment by mreza-dehghani** [comment]
> I'm using the react-native-html-to-pdf package. The pdf works fine in English language but when I change my language to any other language except English then the text is not visible and it shows empty spaces instead of the text.

do you found any solution??
