### ISSUE TITLE
IOS: added one empty page in last position 

### ISSUE THREAD

**Issue by birjubhatt** [christopherdro/react-native-html-to-pdf#277]
when i create pdf in ios that will add one empty page in end of pdf ...and while check android that time its work fine

let options = {
      html: `${DynamicHTML(res, name, logo, symbol)}`,
      fileName: "Products_Pdf_Images",
      directory: "Documents",
    };

    let file = await RNHTMLtoPDF.convert(options);
    props.callBack([`file://${file.filePath}`]);
  };

  function DynamicHTML(res, name, logo, symbol) {
    var html = `<html><head><style>
  *{
    box-sizing: border-box;
  }
  .center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    margin-top: 30px;
    width: 90%;
    height: 700px;
  }
  .card{
    border: 2px solid grey;
    border-radius: 20px;
    min-height: 792px;
    page-break-after: always;
  }
  td{
    min-width: 70px;
    }
  
  </style></head> <body>`;
    console.log("product .length " + product.length);
    for (let i = 0; i < product.length; i++) {
      console.log("i :" + i);

      var logoPresent = logo
        ? `<img src= ${logo} class='inline' width="50" height="50"  style= "position:absolute; bottom: 0; left: 45%;margin-bottom: 10px" >`
        : "";
      html =
        html +
        `<div class = "card">
            <img src= ${res}${product[i].catalog_id}/${
          product[i].file_path
        } class = 'center' alt="Image">
              <div style = "margin: 25px;">
                <table style ="font-size: 20px; ">
                  <tr>
                    <td>Name :</td>
                    <td>${product[i].product_name}</td>
                  </tr>
                  <tr>
                    <td>Desc :</td>
                    <td>${
                      product[i].product_description
                        ? product[i].product_description
                        : "-"
                    }</td>
                  </tr>
                  <tr>
                    <td>Code :</td>
                    <td>${
                      product[i].product_code ? product[i].product_code : "-"
                    }</td>
                  </tr>
                  <tr>
                    <td>Price :</td>
                    <td>${
                      product[i].product_price
                        ? product[i].product_price + symbol
                        : "-"
                    }</td>
                  </tr>
                </table>
                <div style="position: relative; margin-top: 60px;">
                  ${logoPresent}
                  <p class = 'inline' style= "position:absolute; bottom: 0; left: 45%; margin-left: ${
                    logo ? "55px" : "0px"
                  };font-size: 22px;">${name}</p>
                  <img src= ${logo} class ='inline' style="position:absolute; bottom: 0; right: 0;margin-right: 10px; margin-bottom: 10px; opacity: 0.5;" width="50" height="50">
                </div>
              </div>
          </div>`;
    }
    html = html + "</body></html>";

return html;
  }

**Comment by ramkrishnasamanta8** [comment]
This is happening at my side , when I  am creating pdf with multiple page .

**Comment by ramkrishnasamanta8** [comment]
Solved the problem by making changes the line 
for ( int i = 0 ; i < self.numberOfPages  ; i++ ) 
to
for ( int i = 0 ; i < self.numberOfPages - 1  ; i++ ) 
 in the function  
- (NSData*) printToPDF:(NSInteger**)_numberOfPages
                   backgroundColor:(UIColor*)_bgColor pdfType:(NSString*)_pdfType 
within RNHTMLtoPDF.m file in iOS folder within node modules of the corresponding library .

Note : You can pass value from Javascript code  like 

let options = {
            html: htmlCode,
            type: 'default',
            fileName :new Date().getTime(),
            directory: 'Documents',
        };
// passing  " type: 'default' "  as extra param to put condition in the native code 

Then used the "type" params in  iOS Native code  in below function like

**- (NSData*) printToPDF:(NSInteger**)_numberOfPages
                   backgroundColor:(UIColor*)_bgColor pdfType:(NSString*)_pdfType** 

 NSInteger pdfPageCount = self.numberOfPages;
    if([_pdfType isEqualToString:@"custom"]){
      pdfPageCount = pdfPageCount - 1;
    }
    for ( int i = 0 ; i < pdfPageCount  ; i++ )
await RNHTMLtoPDF.convert(options)
