### ISSUE TITLE
Unable open pdf created with img html tag

### ISSUE THREAD

**Issue by Bhumikathiriya** [christopherdro/react-native-html-to-pdf#28]
Hi,

This is great plugin for react native developers to create pdf. I created normal text pdf. I created as expected. 

When I created pdf with html img tag with local image uri,live image url,base64 of image in src attribute ,I m unable to open the pdf.And I note that pdf size is 0 bytes.

**Comment by demonhunterunderdarkness** [comment]
Seems similar with mine, but I can open the PDF file  with no image shown.The img tag is not work

**Comment by esutton** [comment]
On iOS, I am also having trouble with local image resources.  I thought encodeURI would solve the problem by fixing spaces in path to the PNG image file but it did not.
encodeURI replaces spaces in iconPlace path with '%20':

Path to iconPlace image:
`/Users/eddie/Library/Developer/CoreSimulator/Devices/AEF28E16-6D41-4E45-884F-FF98CB0D389C/data/Containers/Data/Application/FA42DE87-E33F-44A0-8A3B-4297E1DB98D9/tmp/RNVectorIcons_Material%20Icons_58719_30#000000@2x.png`

HTML still cannot access image for some reason.  I get an unknown image in the PDF.
`<img src="${state.iconPlace}" />
`

It *does* work if I pass image src as embedded base64 data.  

This base64 approach also fixed a problem with iOS retrieving old images from cache.

```
<img src="data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAACEA
AAlwSFlzAAAWJQAAFiUBSVIk8AAAABxpRE9UAAAAAgAAAAAAAAEsAAAAKAAAASwA
...
glnXgLoqmJDcIiguBjCAigKKAQUjmEAERbKioIAoiBIUQaLEYabr+59LV1PT9oSe" 
 alt="Profile View" style="width:100%;" >
```

**Comment by esutton** [comment]
I found my problem. There must be something in the PNG file name that react-natiive-vector-icons that is not making HTML happy.  Maybe the "@2x.png" or the "#" character??

It works if change file name from
`RNVectorIcons_Material%20Icons_58719_30#000000@2x.png`
to
`iconPlace.png`

const src = '/Users/edward3/Library/Developer/CoreSimulator/Devices/AEF28E16-6D41-4E45-884F-FF98CB0D389C/data/Containers/Data/Application/FA42DE87-E33F-44A0-8A3B-4297E1DB98D9/tmp/iconPlace.png';
