### ISSUE TITLE
Is it possible to use sass or tailwind for css styling?

### ISSUE THREAD

**Issue by xbaldiq** [christopherdro/react-native-html-to-pdf#283]
The inline styling is working fine, but can we use alternative styling method?

**Comment by johnfrades** [comment]
hi @xbaldiq i was able to add tailwind on this thru cdn, more info here https://tailwindcss.com/docs/installation/play-cdn

```
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <h1 class="text-3xl font-bold underline">
    Hello world!
  </h1>
</body>
</html>
```

**Comment by rizki-tabist** [comment]
> hi @xbaldiq i was able to add tailwind on this thru cdn, more info here https://tailwindcss.com/docs/installation/play-cdn
> 
> ```
> <!doctype html>
> <html>
> <head>
>   <meta charset="UTF-8">
>   <meta name="viewport" content="width=device-width, initial-scale=1.0">
>   <script src="https://cdn.tailwindcss.com"></script>
> </head>
> <body>
>   <h1 class="text-3xl font-bold underline">
>     Hello world!
>   </h1>
> </body>
> </html>
> ```

yes, this workaround is working fine on iOS. However, on Android, the tailwind is not loaded. It might be because the javascript is not enabled. https://github.com/christopherdro/react-native-html-to-pdf/issues/239#issuecomment-1058125888
