### ISSUE TITLE
This library is not working in the android SDK 33

### ISSUE THREAD

**Issue by Krunal7918** [christopherdro/react-native-html-to-pdf#303]
**I receive below error in the react native how to resolve it can anyone suggests me**

If download the any pdf shows that in console  

fd cannot be null
never_ask_again

Thanks in advance.

**Comment by ankurbit1997** [comment]
you dont need to ask for strorage permission from sdk level 33 
this error is because of that

**Comment by Krunal7918** [comment]
But if I not ask permission, then again, the app crashes. Then How can I achieve that?

**Comment by Krunal7918** [comment]
You can download the pdf in cache file.
