### ISSUE TITLE
CSS `background-color` and `background` property doesn't work on iOS

### ISSUE THREAD

**Issue by Chr1ssW** [christopherdro/react-native-html-to-pdf#308]
The `background-color` and `background` properties do not work on iOS, but they render fine on Android. When decoded, the returned base64 string also doesn't contain the colors. See the examples below:

```
.invoice-box table tr.heading td {
	background: #eee;
	border-bottom: 1px solid #ddd;
	font-weight: bold;
}
```

## iOS
![image](https://github.com/christopherdro/react-native-html-to-pdf/assets/56091550/da341584-ea93-4e2d-97a7-62238a8c9c30)

## Android 
![image](https://github.com/christopherdro/react-native-html-to-pdf/assets/56091550/6679cc41-5c6a-4d7e-aa7c-d2a953c0a4d7)

**Comment by one-god** [comment]
I am facing the same issue ,background-image not work  on iOS

**Comment by jole141** [comment]
@Chr1ssW @one-god  This solved the problem for me
```
<style>
      * { print-color-adjust:exact !important; }
</style>
```

**Comment by one-god** [comment]
> @Chr1ssW @one-god This solved the problem for me
> 
> ```
> <style>
>       * { print-color-adjust:exact !important; }
> </style>
> ```
thank you so much，it's OK now

**Comment by Chr1ssW** [comment]
This solution indeed works, closing the issue. Thanks to @one-god for the solution!

**Comment by okechukwu0127** [comment]
this worked like a charm for me
