### ISSUE TITLE
does not support  the chinese word

### ISSUE THREAD

**Issue by iamaluckyman** [christopherdro/react-native-html-to-pdf#32]
Thank you for the great component.

My app need to support  the chinese word.
IOS is OK. 
but Android is NG.
Would you like to give some advices?

Thanks.

**Comment by christopherdro** [comment]
Might want to try and took a look at this PR https://github.com/christopherdro/react-native-html-to-pdf/pull/30. Looks like you can attach your own custom font that should work.

**Comment by tza17313** [comment]
one tips: 
in your html,you need set font family in all used tag , like this:

html part:
```html
<style>
        body{
            font-size: 11px;
        }
        div,h1,h2,p{
            font-family: SimSun;
        }
</style>
<h1>测试文字</h1>
<h2>测试文字</h2>
<p>测试文字</p>
```
javascript part :
```javascript
 let options = {
            html: getHtml({}),
            fileName: 'test',
            directory: 'docs',
            fonts: ['/fonts/SimSun.ttf']
        };
RNHTMLtoPDF.convert(options).then((result) => {
            console.log(result)
        }).catch((err) => {
            console.log(err)
        })
```
如果直接给body设置 font-family 是没效果的，并不会集成  😂
