### ISSUE TITLE
Can we use chart?

### ISSUE THREAD

**Issue by maltz** [christopherdro/react-native-html-to-pdf#35]
I made health care app that use chart.
And then, I want to export pdf file displayed that chart.
I use react-native-highcharts.

Is there any nice way ?

**Comment by DenizTemizer** [comment]
I don't think that this is something you want to do...
Would need a lot of refactoring and cause a big overhead.
Looks like the only nice way would be using a css library like [chart css](https://theus.github.io/chart.css/), generating the html on your own and printing this on pdf.

However, I don't know how well iText will handle complex css.

**Comment by christopherdro** [comment]
One way is to take a screenshot of your view and use that image to create the pdf.

**Comment by matias4205** [comment]
> 
> 
> One way is to take a screenshot of your view and use that image to create the pdf.

I DID THIS! 😁
