### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by andreatoso** [christopherdro/react-native-html-to-pdf#36]
I installed the package correctly and it works in iOS, but when I execute the code in Android I got this error: ` Possible Unhandled Promise Rejection (id: 0): TypeError: undefined is not an object (evaluating _reactNativeHtmlToPdf2.default.convert)` How can I fix this error?

**Comment by christopherdro** [comment]
@andreatoso Can you share your code?

You'll need to wrap your call in a try/catch to log what the actual error is. I should update the docs to reflect this but it should look something like.

```
try {
  let file = await RNHTMLtoPDF.convert(options)
  console.log('Success', file)
} catch (err)
  console.log(err)
}
```

**Comment by rpgpunzalan** [comment]
@christopherdro  I am having the same problem. Here's the error logged after catching 

[TypeError: null is not an object (evaluating 'RnHtmlToPdf.convert')]
