### ISSUE TITLE
Support Html Image Tag

### ISSUE THREAD

**Issue by andrienpecson** [christopherdro/react-native-html-to-pdf#38]
Everytime I add html image tag with external link of image to the html string, it does not generate pdf.

**Comment by gustavorozolin** [comment]
@andrienpecson 
Its work with internal url?

Thanks

**Comment by andrienpecson** [comment]
How about external image url?

**Comment by andrienpecson** [comment]
I confirmed that this is working. All we need is to close every tags. Thanks

**Comment by DanielDoe** [comment]
@andrienpecson You mean it works on external image url too??

**Comment by andrienpecson** [comment]
@DanielDoe Yes, it works. I'm using external image URL

**Comment by DanielDoe** [comment]
Please @andrienpecson 
could you help me like send me a snippet lemme try and figure mine out.

**Comment by DanielDoe** [comment]
@andrienpecson i got it working was copying a wrong url
thanks tho

**Comment by RShah512** [comment]
@andrienpecson Facing a similar issue. HTML image tag doesn't show image in PDF whether I use internal or external image. Could you help me with a code snippet?
