### ISSUE TITLE
Error after adding libraries

### ISSUE THREAD

**Issue by sterndm** [christopherdro/react-native-html-to-pdf#4]
Something goes wrong after I add RNHTMLtoPDF.xcodeproj to the project and libRNHTMLtoPDF.a to libraries. Any idea what this error means?

/node_modules/react-native-html-to-pdf/RNHTMLtoPDF/RNHTMLtoPDF.m:132:27: error: too few arguments to block call, expected 3, have 1
        _rejectBlock(error);
        ~~~~~~~~~~~~      ^

**Comment by wootwoot1234** [comment]
I'm getting this error too.  I just upgraded from react native 0.17 to 0.20.

**Comment by sterndm** [comment]
wootwoot1234, 
were you able to fix it?

**Comment by wootwoot1234** [comment]
Yes.  I need to submit a push request with the fix.

This will fix the error.  Change line 132 of RNHTMLtoPDF.m from:

```
        _rejectBlock(error);
```

to:


```
        _rejectBlock(RCTErrorUnspecified, nil, RCTErrorWithMessage(error.description));
```

**Comment by sterndm** [comment]
Yes,
This fixed it! Thanks so much :)

**Comment by wootwoot1234** [comment]
@sterndm don't close this issue until it's fixed in the code.  Do you mind reopening it and letting @christopherdro close it when a fix has been committed?  Thanks!

**Comment by sterndm** [comment]
Oh, my bad. Reopened it.

**Comment by sterndm** [comment]
Quick question. I'm now making an android version of my app. Does this work on android?

**Comment by christopherdro** [comment]
Not ATM :( Gonna look into it when I get some free time.

**Comment by christopherdro** [comment]
Not at the moment. :( Will try to add support when I get some free time.

**Comment by sterndm** [comment]
Would be much appreciated! You're my only hope on generating a PDF in RN :)
