### ISSUE TITLE
Footer Text

### ISSUE THREAD

**Issue by andrienpecson** [christopherdro/react-native-html-to-pdf#52]
How can we add footer text?

**Comment by FlaviooLima** [comment]
I found a work around.
The  ideia is use this package to create the pdf and we set the margin for each page with the size the header and/or footer.

To set the margin : 

In iOS we use the padding option of this package. (I'm gonna try to fork the possibility to set each side: Left, Top, Bottom, Right padding).


In Android we use this style to set margins:
  ```
   '<style>' +
      '@page{' +
      'background-color: red;' +
      'margin-left: 20pt' +
      'margin-right: 20pt' +
      'margin-top: 20pt;' +
      'margin-bottom: 20pt' +
      'padding:0px;' +
      '}' +
      '</style>'
```
Now we have a pdf file with empty spaces of the size that you give (20pt in my case). All we need is to edit the PDF file and add the footer and header.

. we gonna jump to this package [react-native-pdf-lib](https://github.com/Hopding/react-native-pdf-lib).

Where we have an option to edit every single page of the pdf.
and now we add the footer and the header in the right position.

Done!!!!

If you have a better work around i would love to hear and update my code :)

**Comment by experionarjun** [comment]
@FlaviooLima How do we know how many pages are there in an existing document though?

**Comment by experionarjun** [comment]
Hey, I need to add a footer to every page of the document and I guess the react-native-pdf-lib only support modifying specific page numbers or an array of pages. The document I am creating using RNHtmlToPDF have dynamic content and the pages would change depends on the content.

**Comment by desarrollospyro** [comment]
@experionarjun +1 . Have you obtained any results? Thank you!

**Comment by harshav-acco** [comment]
@experionarjun +1. Did you get any results or did you find any work arounds? Thank you!
