### ISSUE TITLE
Problem with img element in Android

### ISSUE THREAD

**Issue by inventrix** [christopherdro/react-native-html-to-pdf#53]
Hello. When I use an img tag, it is displayed in iOS but it is not displayed in Android. I have created a repo for this bug. You can find it here: https://github.com/inventrix/qrError

In the [index.js](https://github.com/inventrix/qrError/blob/master/index.js) file I am rendering a QR code and a button. When the button is pressed, firstly I save the QR code as a png file. Then I create a PDF file that contains this QR file. I did not include the code that displays the generated PDF file but when I pull it out by using 'adb pull' QR image is not displayed in the generated PDF.

**Comment by hasancanozkan** [comment]
did you get a solution for this or what did you change?? I have a similar one..

**Comment by inventrix** [comment]
I am using this fork: https://github.com/IslamSalah/react-native-html-to-pdf
