### ISSUE TITLE
Manual paging support?

### ISSUE THREAD

**Issue by dzuncoi** [christopherdro/react-native-html-to-pdf#55]
I jump into a problem currently: **set paging manually**
Eg: (assume I predefined page size, as options `width` and `height`). I have 2 chapters, I need each chapter to be placed on separate pages. If `chapter 1 height > options.height` then it will render 2 pages, 1st page is full of content, 2nd page is remaining content, the rest is blank. Chapter 2 will start from 3rd page.

How can we solve this problem? I gonna modify native code but I'm not familiar with Objective C

**Comment by master-caster** [comment]
I don't know if that helps but....

i use a <div></div> for each page and set the style width to 100%.

So everthing within the containers will be rendered on one page.
Everything outside the container will create a new page.

Fells like some kind of a workaround but at least it is reliable.

**Comment by esutton** [comment]
@dzuncoi Using CSS seems to work for page breaks on iOS and Android.

Disclaimer: I am not a CSS or HTML expert and this may be bad or wrong advice.
````        
const cssStyleSheet = `
<style type="text/css" >
div.img {
    display: block;
    max-width:230px;
    max-height:230px;
    width: auto;
    height: auto;
    page-break-before: auto; 
    page-break-after: auto; 
    page-break-inside: avoid;     
}
img {
  page-break-before: auto; 
  page-break-after: auto; 
  page-break-inside: avoid; 
}
</style>`;

let html = `<!DOCTYPE html><head><title>${borePlan.name}</title>${cssStyleSheet}</head>`;
htmlText += '<h1>This is Page One</h1';
...
htmlText += pageBreakWithPageNumberBefore();
htmlText += '<h1>This is Page Two</h1';
...
`````


```
let _globalPageNumber = 0;
function pageBreakWithPageNumberBefore() {
  _globalPageNumber += 1;
  return `<p style="page-break-before: always;" align=center>Page ${_globalPageNumber}</p>`;
}
```

Question: Any advice on how to make PDF generate as landscape on Android?  

I have it working on iOS but Android stays in portrait.  

Perhaps Android has different units for page size?

This works on iOS
````
const options = {
    height: 800, /* Optional: 800 sets the height of the DOCUMENT that will be produced, Default: 612 */
    width: 1056, /* Optional: 1056 sets the width of the DOCUMENT that will produced, Default: 792 */
    padding: 24 /* Optional: 24 is the # of pixels between the outer paper edge and
};
````

**Comment by dzuncoi** [comment]
@esutton Thanks for the solution, you make my day :) 
About Android, I don't find they use `width` & `height` to generate PDF, that's sad

**Comment by esutton** [comment]
@dzuncoi I forked this project and updated iTextPdf libraries used under Android.

I think it would be pretty easy to modify to make it take the width and height options to create a Rectangle and pass to new Document().

Currently I have hardcoded it to US letter landscape size just to prove it could work.

https://github.com/esutton/react-native-html-to-pdf

````
Rectangle pageSizeUsLetterLandscape = new Rectangle(861, 612);
Document doc = new Document(pageSizeUsLetterLandscape);
````

**Comment by dzuncoi** [comment]
Great, it would be nice if you can open PR for this

**Comment by esutton** [comment]
@dzuncoi That would be a good exercise to help educate myself on how git PR's work.

**Comment by christopherdro** [comment]
@esutton A PR would be great! 
We can expose an option to set the document size and default to A4.

You should be able to open one up directly from your forked repo.
