### ISSUE TITLE
How to remove document margin?

### ISSUE THREAD

**Issue by ariona** [christopherdro/react-native-html-to-pdf#59]

**Comment by christopherdro** [comment]
Have you tried the `padding` options? That is iOS specific though.

**Comment by ariona** [comment]
Iam deloping for android. Need to ditch the source code btw. 😁

**Comment by christopherdro** [comment]
Not sure I follow but there is PR open that changes a few things and it looks like it might support margins. 

https://github.com/christopherdro/react-native-html-to-pdf/pull/51
