### ISSUE TITLE
Error after upgrading to 0.6.0

### ISSUE THREAD

**Issue by remicoges** [christopherdro/react-native-html-to-pdf#65]
Hello,

After upgrading to 0.6.0, I am unable to generate a pdf and get this error on android : 

> Fatal Exception: java.lang.IllegalArgumentException: fd cannot be null
       at org.chromium.android_webview.AwPdfExporter.exportToPdf(AwPdfExporter.java:53)
       at org.chromium.android_webview.AwPrintDocumentAdapter.onWrite(AwPrintDocumentAdapter.java:70)
       at android.print.PdfConverter$1.onPageFinished(PdfConverter.java:67)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:546)
       at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:201)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6540)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Is this release broken or am I the only one getting this error ?

**Comment by IslamSalah** [comment]
Are you sure that the directory, which will contain the pdf file, is already exist before converting ?

**Comment by remicoges** [comment]
Yes, when I switch back to 0.5.0 it works fine, and doesn't crash

**Comment by remicoges** [comment]
It now works,

**Comment by pramodkr123** [comment]
i am getting the same issue in Samsung Galaxy Note9. How could I resolve this?

**Comment by RShah512** [comment]
Same issue for android device. Any fix? Currently running ver 0.6.0

**Comment by pramodkr123** [comment]
> 
> 
> Same issue for android device. Any fix? Currently running ver 0.6.0

ParcelFileDescriptor.open(**file**, ParcelFileDescriptor.MODE_READ_WRITE);
check the **file name** is correct.
In file name not should be **"/"**

**Comment by firdaussoberi** [comment]
Same error in Android. Not working with 0.8.0 . Reverted to 0.6.0 and it works. Here's my js code:
```javascript
html_str = 'some html str';
name = 'some name';
		let options = {
			html: html_str,
                        fileName: name,
			directory: 'Documents',
			base64:true,			
		};

    if(Platform.OS === 'android'){
        RNHTMLtoPDF.convert(options).then(path => {
          //alert(JSON.stringify(filePath));
          //alert(JSON.stringify(path));    
                const {navigate} = this.props.navigation;     
                navigate('PDFOpen', {pdfLink: path.filePath, base64PDF: path.base64});        
        })
    }else{
        RNHTMLtoPDF.convert(options).then(path => {
             //alert(name);
            // RNFetchBlob.fs.dirs.DocumentDir it's getting the documents folder from internal storage
            // RNFetchBlob.fs.dirs.CacheDir it's getting the cache folder from internal storage            
            let filePath = RNFetchBlob.fs.dirs.CacheDir + '/' + name + '.pdf';
            //alert('*** ' + filePath + ',*** ' + RNFetchBlob.fs.dirs.DocumentDir + ',*** ' + path.filePath );
            RNFetchBlob.fs.writeFile(filePath, path.base64, 'base64')
            .then(response => {
                    //alert(path.base64);
                    //alert(JSON.stringify(response))
                    const {navigate} = this.props.navigation;     
                    navigate('PDFOpen', {pdfLink: filePath, base64PDF: path.base64});                      
                    console.log('Success Log: ', response);
            })
            .catch(errors => {
                    console.log(" Error Log: ", errors);
            })

        })

    }
```

**Comment by IslamSalah** [comment]
@firdaussoberi Have you check [this case](https://github.com/christopherdro/react-native-html-to-pdf/issues/65#issuecomment-369629245)?

**Comment by firdaussoberi** [comment]
@IslamSalah I used the standard directory:'Documents' in options. For iOS somehow it can't read rnhtml directory option that's why i used rnfetchblob. I also tried cachedir for android with rnfetchblob but didn't work in 0.8.0.  For some reason 0.60 works

**Comment by MahbbRah** [comment]
Not working. I got the same issue!

**Comment by MahbbRah** [comment]
First thing is, it doesn't work on latest RN version greater than 0.6, Second thing is if you don't  prompt and take permission from user for storage then you'll see the same error message. so if you revert back to 0.6 or earlier. you must have to take the permission  through this https://reactnative.dev/docs/permissionsandroid.

**Comment by premsekarpk** [comment]
fdsdfsdf

**Comment by ClaudioVigliarolo** [comment]
Here is the solution
**Steps:**
1 **downgrade** the react-native-html-to-pdf to version 0.8

2 make sure you have all the permission in the **androidmanifest.xml**


```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <application
    android:requestLegacyExternalStorage="true"
```
.....




**3 try out this piece of code**. Please keep in mind that the use of **isPermitted** function is required. Otherwise it would just throw an errror

  ` // Example to Make PDF in React Native from HTML Text
// https://aboutreact.com/make-pdf-in-react-native-from-html-text/

// Import React
import React, {useState} from 'react';
// Import required components
import {
  SafeAreaView,
  Text,
  TouchableOpacity,
  View,
  StyleSheet,
  Image,
  PermissionsAndroid,
  Platform,
} from 'react-native';

// Import HTML to PDF
import RNHTMLtoPDF from 'react-native-html-to-pdf';

const App = () => {
  const [filePath, setFilePath] = useState('');

  const isPermitted = async () => {
    if (Platform.OS === 'android') {
      try {
        const granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
          {
            title: 'External Storage Write Permission',
            message: 'App needs access to Storage data',
          },
        );
        return granted === PermissionsAndroid.RESULTS.GRANTED;
      } catch (err) {
        alert('Write permission err', err);
        return false;
      }
    } else {
      return true;
    }
  };

  const createPDF = async () => {
    if (await isPermitted()) {
      let options = {
        //Content to print
        html:
          '<h1 style="text-align: center;"><strong>Hello Guys</strong></h1><p style="text-align: center;">Here is an example of pdf Print in React Native</p><p style="text-align: center;"><strong>Team About React</strong></p>',
        //File Name
        fileName: 'test',
        //File directory
        directory: 'docs',
      };
      let file = await RNHTMLtoPDF.convert(options);
      console.log(file.filePath);
      setFilePath(file.filePath);
    }
  };

  return (
    <SafeAreaView style={{flex: 1}}>
      <Text style={styles.titleText}>
        Example to Make PDF in React Native from HTML Text
      </Text>
      <View style={styles.container}>
        <TouchableOpacity onPress={createPDF}>
          <View>
            <Image
              //We are showing the Image from online
              source={{
                uri:
                  'https://raw.githubusercontent.com/AboutReact/sampleresource/master/pdf.png',
              }}
              style={styles.imageStyle}
            />
            <Text style={styles.textStyle}>Create PDF</Text>
          </View>
        </TouchableOpacity>
        <Text style={styles.textStyle}>{filePath}</Text>
      </View>
    </SafeAreaView>
  );
};

export default App;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  titleText: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    paddingVertical: 20,
  },
  textStyle: {
    fontSize: 18,
    padding: 10,
    color: 'black',
    textAlign: 'center',
  },
  imageStyle: {
    width: 150,
    height: 150,
    margin: 5,
    resizeMode: 'stretch',
  },
});`
