### ISSUE TITLE
Non latin characters garbled after 0.6.0 upate

### ISSUE THREAD

**Issue by remicoges** [christopherdro/react-native-html-to-pdf#68]
Hello 

With the removal of iText, generated PDF including chinese chars now look like [this](https://i.gyazo.com/8f10fa3b857f48db847d4f3eb6e38462.png).

I have a custom font supporting these chars, and it's well included but I don't know why it is wrongly displayed.

Thanks

**Comment by remicoges** [comment]
It works by encoding all chars to HTML entities, but shouldn't it work out of the box ?

**Comment by pichaisodsai** [comment]
@remicoges Could you please tell me how can you add a custom font? Where to put fonts in the Android and what path should we enter in the 'fonts' options?

**Comment by remicoges** [comment]
@pichaisodsai 
I used 
 `import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';`
to access my font

`fonts: [resolveAssetSource(require('../../assets/fonts/Overpass-Regular.ttf')).uri],`

and in the `options` object I added the fonts like this.

` @font-face {
    font-family: 'Overpass Regular';
    font-style: normal;
    font-weight: 400;
    src: url('Overpass-Regular.ttf');
  }`

And then in the HTML to use it

**Comment by hannanstd** [comment]
hi
i have this problem. please help

**Comment by IslamSalah** [comment]
@hannanstd if you can share a very simple code sample, may be git repo, which reproduces the issue, it will be super awesome.

Meanwhile, have you checked this [tip](https://github.com/christopherdro/react-native-html-to-pdf/issues/68#issuecomment-370419650)?

**Comment by hannanstd** [comment]
finaly i changed my font to base64 via https://transfonter.org/ and i putted font-face with base64 ttf
:(

**Comment by Koniouchine** [comment]
> @pichaisodsai
> I used
> `import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';`
> to access my font
> 
> `fonts: [resolveAssetSource(require('../../assets/fonts/Overpass-Regular.ttf')).uri],`
> 
> and in the `options` object I added the fonts like this.
> 
> ` @font-face { font-family: 'Overpass Regular'; font-style: normal; font-weight: 400; src: url('Overpass-Regular.ttf'); }`
> 
> And then in the HTML to use it

I'm trying to use your solution. However I'm confused when you say you used: 

@font-face { font-family: 'Overpass Regular'; font-style: normal; font-weight: 400; src: url('Overpass-Regular.ttf'); }

in 'options'. Where in options did you use that if there is no property for it? Did you not use resolveAssetSource for 'fonts:'? 
Also resolveAssetSource throws an error. 

If you ran into any of this, and have some pointers, that would be great thanks.

**Comment by sepowitz** [comment]
Has anyone had any success loading custom fonts following this thread? I'm trying to get custom fonts working on Android to no avail.

any help would be much appreciated!

**Comment by Koniouchine** [comment]
> Has anyone had any success loading custom fonts following this thread? I'm trying to get custom fonts working on Android to no avail.
> 
> any help would be much appreciated!

Yes I managed to get it working. 
However for me to get it to work I had to convert my fonts into base64 using a service like https://transfonter.org/ (I simply uplaod my .ttf, and then set Base64 to be 'ON'. 

Then I open the resulting file, copy the resulting string (it's really long) into a <style></style> stylesheet in my project like so:

`const AntDesign = <style>
@font-face {
    font-family: 'AntDesign';
    src: url(data:font/truetype;charset=utf-8;base64, *base64 goes here*  )
    font-weight: normal;
    font-style: normal;
} </style>`
The base64 encoding will be very long, and look like random characters. 
ex. AAEAAAANAIAAAwBQRkZUTYMgDqMAAQFsAAAAHEdERUYAKQE0AAEBTAAAAB5PUy8yVudL6AAAAVgAAABWY21hcDigh20AAAV0AAA

Only significantly longer


I did not use resolveAssetSource, and I did not put the fonts into the 'Fonts' property of 'options' as it did not work for me.

**Comment by sepowitz** [comment]
> > Has anyone had any success loading custom fonts following this thread? I'm trying to get custom fonts working on Android to no avail.
> > any help would be much appreciated!
> 
> Yes I managed to get it working.
> However for me to get it to work I had to convert my fonts into base64 using a service like https://transfonter.org/ (I simply uplaod my .ttf, and then set Base64 to be 'ON'.
> 
> Then I open the resulting file, copy the resulting string (it's really long) into a <style></style> stylesheet in my project like so:
> 
> `const AntDesign = <style> @font-face { font-family: 'AntDesign'; src: url(data:font/truetype;charset=utf-8;base64, *base64 goes here* ) font-weight: normal; font-style: normal; } </style>`
> The base64 encoding will be very long, and look like random characters.
> ex. AAEAAAANAIAAAwBQRkZUTYMgDqMAAQFsAAAAHEdERUYAKQE0AAEBTAAAAB5PUy8yVudL6AAAAVgAAABWY21hcDigh20AAAV0AAA
> 
> Only significantly longer
> 
> I did not use resolveAssetSource, and I did not put the fonts into the 'Fonts' property of 'options' as it did not work for me.

Interesting solution! I will give this a shot and post an update if it manages to work for me. Really appreciate your help @Koniouchine
