### ISSUE TITLE
Many issues...

### ISSUE THREAD

**Issue by boliveira** [christopherdro/react-native-html-to-pdf#73]
Hi,

I have many issues when using this library on Android, for instance:

- fileName argument is not used to build the final filename when the directory is not "docs".
- Not able to save in the user "Downloads" folder.
- Application crashes when it can't create the directory to the file. It should check the result of the mkdir call in convert and return an error if it didn't succeed instead of crashing.

Is it possible to add an option to save to the user Downloads folder? Thanks.

**Comment by Ligia-Andreica** [comment]
Take a look at this PR: https://github.com/christopherdro/react-native-html-to-pdf/pull/81 and see if it helps you.

**Comment by raphaelhovsepyan** [comment]
@boliveira in android default folder for downloads is "Download"(not plural).

**Comment by alitsvin** [comment]
I solved the issue by adding permission request before converting
