### ISSUE TITLE
pdf hyperlink from a href

### ISSUE THREAD

**Issue by SaruwatariSagittario** [christopherdro/react-native-html-to-pdf#76]
Hi, thanks for the library
it save me few nights of headache from drawing purely on pdf.
I want to ask, is it possible to put hyperlink to generated pdf based on HTML a href element?

I tried but it only generate blue with underline text without redirection upon click

Thanks..

**Comment by wardzxzxc** [comment]
Hi,

I'm currently facing the same issue as well. It seems to not work on iOS only. 

I also realised that the href value is not read but rather, the url within the <a> tag is read.

Hope someone would be able to share their solution if they managed to work around it.

Thank you.

**Comment by anoop-sharma** [comment]
Is there any solution to this issue?

**Comment by Osamasomy** [comment]
any solution? i face same problem
