### ISSUE TITLE
Not compatible with "Create-React-Native-App"

### ISSUE THREAD

**Issue by johnnetr** [christopherdro/react-native-html-to-pdf#78]
Currently anything with "React-Native Link" has to be ejected, if you installed with "create-react-native-app", in order to use that library. My whole project is on that installation setting, anyway to use this library without ejecting? Appreciate any solution!

**Comment by johnnetr** [comment]
Update: I see that the example is installed by react-native init. Is there an installation guide for those installed with create-react-native-app? Since the files and folder are very different depending on which installation command.

**Comment by johnnetr** [comment]
Update2: tried console.log(NativeModules.RNHTMLtoPDF); and still got undefined.

**Comment by johnnetr** [comment]
Update3: I tried the same process but installed with react-native init and it worked. However my whole project is on the other installation, create-react-native-app. If anyone got a solution, I appreciate that.

**Comment by johnnetr** [comment]
Currently anything with "React-Native Link" has to be ejected from the installation command "create-react-native-app" in order to use that library. My whole project is on that installation setting, anyway to use this library without ejecting? Appreciate any solution!

**Comment by christopherdro** [comment]
Unfortunately not. The majority of the code for this library is native so you will have to eject to use it.
