### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by sterndm** [christopherdro/react-native-html-to-pdf#8]
When is android support coming?

**Comment by christopherdro** [comment]
Hey there! I'm quite busy at the moment and don' think I'll get to it anytime soon. I'll be more than happy to take a look at a PR if you'd like to put one together.

**Comment by parkerdan** [comment]
@sterndm https://github.com/parkerdan/react-native-html-to-pdf

**Comment by christopherdro** [comment]
@parkerdan Sweet! Would you be open to submitting a PR adding android support?

**Comment by christopherdro** [comment]
Available in v0.2.0
