### ISSUE TITLE
It doesn't work()

### ISSUE THREAD

**Issue by schect404** [christopherdro/react-native-html-to-pdf#80]
It just can not get RNHTMLtoPDF from the package.
So error is
undefined is not an object (evaluating '_reactNativeHtmlToPdf.RNHTMLtoPDF' )

**Comment by malashkevich** [comment]
I got the same error. Double checked that everything was added.

**Comment by rikur** [comment]
You get that error if a native library wasn't linked properly.

`watchman watch-del-all` and `react-native start --reset-cache` should help. Sometimes I need to nuke the build dirs `ios/build` and `android/app/build`.

**Comment by rikur** [comment]
Ahh my bad! I just got the error myself. The module is not a default export, so instead of:
```
import RNHTMLtoPDF from 'react-native-html-to-pdf'
```
You need to:
```
import { RNHTMLtoPDF } from 'react-native-html-to-pdf'
```

**Comment by rikur** [comment]
@christopherdro the docs should be updated (or the default export added). Very sorry, am too busy to create a PR  myself right now.

**Comment by themakerman** [comment]
I am getting an error at RNHTMLtoPDF.convert(options) that convert is undefined.
Also imported the module this way --> `import { RNHTMLtoPDF } from 'react-native-html-to-pdf'`

When i import `import RNHTMLtoPDF from 'react-native-html-to-pdf'`, the app is crashing

**Comment by themakerman** [comment]
ok solved it by upgrading android studio. Guys if you face any issues making it work try opening the project in android studio. Fix any needful issues. In my case gradle was old and this library needed latest gradle with android studio 3.0. In my case mine was android studio 2.0. 

Upgrading really helped. Thanks.

**Comment by lucasriondel** [comment]
@themakerman I tried to do the same, and my app is still crashing. I have updated gradle with AS, still not working. Could you tell me if you have the same line in your android/build.gradle ? 

```
dependencies {
    classpath 'com.android.tools.build:gradle:3.1.3'
}
```

**Comment by lucasriondel** [comment]
ok, i managed to make it work, the issue was that i was using `directory: 'docs'` in the options passed to the `convert()` method. But now, my pdf is saved in the app's cache, which isn't convenient.

one thing that would be good to investigate @christopherdro is why this part of your code : 
```
if (options.hasKey("directory") && options.getString("directory").equals("docs")) {
        String state = Environment.getExternalStorageState();
          File path = (Environment.MEDIA_MOUNTED.equals(state)) ?
                  new File(Environment.getExternalStorageDirectory(), Environment.DIRECTORY_DOCUMENTS)
                  : new File(mReactContext.getFilesDir(), Environment.DIRECTORY_DOCUMENTS);

        if (!path.exists()) path.mkdir();
        destinationFile = new File(path, fileName + ".pdf");
      }
```

is making the app crash.

**Comment by lucasriondel** [comment]
ok, after investigation, this part is not causing the problem, it is the PdfConverter instance's method `convert()` that's making the app crash. But it is working fine in local storage though, even if I don't have a way to access it on my device. Maybe this is permission related..? I have added 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` and `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />` to my `AndroidManifest.xml` file, but nothing changes, I really don't know what is happening.

**Comment by themakerman** [comment]
@lucasriondel Try using expo's build in print api if you are using them.......Worked out of the box for me :)

**Comment by Daniel0liver** [comment]
> Você já tentou executar o projeto de exemplo?
> 
> Caso contrário, verifique se você incluiu os arquivos nativos.
> 
> Consulte: https://github.com/christopherdro/react-native-html-to-pdf#option-2-manual

this is solvable my problem

**Comment by ZainabShakeel** [comment]
im facing issues **RNHTMLtoPDF is undefined** although my app is latest versions of reactnative
