### ISSUE TITLE
Problem with iOS

### ISSUE THREAD

**Issue by AbhishekDS-Userfacet** [christopherdro/react-native-html-to-pdf#83]
Unable to create PDF in iOS but it is working on Android perfectly!

How to resolve this?

**Comment by gmchaturvedi1** [comment]
+1 i am facing the same

**Comment by AppirioBruce** [comment]
+1 same issue

**Comment by AaronDRS** [comment]
Hi, I'm wondering if there is some fix for this. This is not generating any PDF to iOS devices.
Please fix it.

**Comment by AaronDRS** [comment]
Hi @christopherdro, here is my code please let me know if I'm missing something.

`    const options = {
      html: `<style>*{ font-family: 'Montserrat';}</style><body>
      <h1>${name} Item</h1>
      <div>${body}</div>
      </body>`,
      fileName: `${name}_item`,
      directory: 'Documents',
    }
const file = await RNHTMLtoPDF.convert(options)
`
Great Library.

**Comment by tobyhinloopen** [comment]
Might be related or not, but I found that using factional style values (EG `-33.8990219px`) caused the `convert` function to hang infinitely for me, while rounded values worked fine.

That was a fun day debugging...

**Comment by ptupi** [comment]
+1

**Comment by anurgsrivastava** [comment]
@tobyhinloopen, Thank you that was very helpful. Along with that, for me when margins were given in percentage(%), it was freezing. But after changing it to pixels(px), it started working.

**Comment by puneetkansal04** [comment]
Hi,

In the IOS it is creating files and storing in iOS

            directory: (Platform.OS === 'ios') ? 'Documents' : 'Downloads',


In the simulator I am able to see it. But in the real device iOS I am not able to find it. So let me know how can I get the iOS file store in the IOS device.
