### ISSUE TITLE
Base64 string is invalid for Android

### ISSUE THREAD

**Issue by katwal-dipak** [christopherdro/react-native-html-to-pdf#85]
1. able to convert HTML to PDF in both android & iOS.
2. base64 string is valid for iOS.

I am able to send base64 string as attachment with `Send Grid` in iOS. But it doesn't work with base64 string of pdf file in android. I can confirm there is no issue with `Send Grid` as I tested manually adding the base64 string from iOS and tested with android which works perfectly fine.

**Comment by iPhaeton** [comment]
The same issue here. Any ideas?

**Comment by katwal-dipak** [comment]
@iPhaeton I used `react-native-fetch-blob` to convert into `base64Data`
