### ISSUE TITLE
looping data inside options -> html

### ISSUE THREAD

**Issue by demm1** [christopherdro/react-native-html-to-pdf#86]
i'm working an apps that can make an invoice,
now i'm stuck at looping the product inside options at the html.

because the for function is not looping, it only run once

could someone guide me how to fix this, or maybe i should choose another npm?
thanks

**Comment by demm1** [comment]
nvm, i found the solution, need to make a function.

**Comment by shivamkulkarni26091994** [comment]
i fetch the data in api, how to give that data inside of html

**Comment by anastely** [comment]
@demm1  I make a function but i got undefined in the PDF file although in console log i can see all items, How u handle it?
