### ISSUE TITLE
directory: 'docs' Crashes the application!

### ISSUE THREAD

**Issue by mrxrinc** [christopherdro/react-native-html-to-pdf#90]
I used this module 1 month ago and it went so good , already passed the testing team and we published the application. some days ago I saw crash reports and found out that exporting pdf simply not working anymore and crashes the app! I began to modify until finding the reason that is the directory! 

```
let options = {
        html: <p>Some text</p>,
        fileName: 'pdfFile',
        directory: 'docs',
}
```

If I remove directory line or change it to not to be 'docs', it will export a pdf file to the system cache directory:
/data/user/0/com.appName/cache/

also changing it to 'Documents' didn't solve the problem and I still get the file at cache directory.  
why this happened and why the app cannot move the exported file from cache to the /Documents  directory??

**Comment by christopherdro** [comment]
I'm guessing this is an issue on Android? If so, did you recently change the target SDK versions in build.grade?

Also, what version are you currently using?

**Comment by mrxrinc** [comment]
yes, exactly on android. this is my environment:
react native 0.55.4,
react-native-html-to-pdf: "^0.6.0",
targetSDK: 26,
operating system: windows 10

actually my target sdk was 23 but as I submitted the application to play store, they said it must be 26, so I changed it and its more than likely that u guessed right, it could be the potential reason of not recognition "directory: docs".

how can we fix it without decreasing the target SDK number?

**Comment by mrxrinc** [comment]
actually I reduced the compile sdk number also target sdk number but nothing changed !

**Comment by fa16mscs0004** [comment]
Hi mrxrinc do you found any solution ?

**Comment by mrxrinc** [comment]
no really, waiting to an answer and just disabled the pdf export section temporarily in my application.
the exact problem is that react-native-html-to-pdf not working when u set ur target sdk to anything except than 22 ! 
while play store forces u to set it to 26.

**Comment by christopherdro** [comment]
The library will need to be updated to use the new FileProvider API.

https://developer.android.com/reference/android/support/v4/content/FileProvider

**Comment by Gazfay** [comment]
Fixed here - https://github.com/Gazfay/react-native-html-to-pdf-fixed

**Comment by chienvu123** [comment]
> Fixed here - https://github.com/Gazfay/react-native-html-to-pdf-fixed

app not crash, but i can't find filePath in result, it is temporary directory

**Comment by wmarino13** [comment]
> Fixed here - https://github.com/Gazfay/react-native-html-to-pdf-fixed

How do i use your fix?

**Comment by Gazfay** [comment]
@wmarino13 
1. run `npm uninstall react-native-html-to-pdf-fixed` 
2. in package.json add `"react-native-html-to-pdf": "git+https://github.com/Gazfay/react-native-html-to-pdf-fixed.git"` 
3. run `npm install`

**Comment by apamphilon** [comment]
@christopherdro Do you have any plans to add this fix into this repository?

**Comment by apamphilon** [comment]
> Fixed here - https://github.com/Gazfay/react-native-html-to-pdf-fixed

Is there a reason that this was forked instead of submitting a pull request?
