### ISSUE TITLE
same version issue i think not supported on 26

### ISSUE THREAD

**Issue by fa16mscs0004** [christopherdro/react-native-html-to-pdf#91]
I am having same problem with 
"react-native": "0.55.4",
supportLibVersion = "26.1.0"

it gives this directory which is not even exist
/storage/emulated/0/Documents/new.pdf

Do you guys have found any solution  ??

**Comment by christopherdro** [comment]
Duplicate https://github.com/christopherdro/react-native-html-to-pdf/issues/90
