### ISSUE TITLE
images are not shown in pdf file

### ISSUE THREAD

**Issue by fedoud32** [christopherdro/react-native-html-to-pdf#92]
i'm using firebase for hosting my images and when i set an image in html it doesn't show , can you help me please , there must be a probem showing images

**Comment by sonipreshita** [comment]
I have been passed with the same problem so I converted my image into **base64** and it worked for me.
You can work this one

**Comment by fedoud32** [comment]
can u show me how to turn images url to base 64

**Comment by sonipreshita** [comment]
`import RNFS from 'react-native-fs';
componentWillMount() {
        RNFS.readFile('/data/user/0/com.sensitivesweets/files/42ea1ec932d5c8cd74423d7361ceb412.png', "base64")
            .then(res => this.setState({ imageData: res }))  //res will contain base64 with data:/image/*:base64;..
    }`

**Comment by VitalieStirbu** [comment]
how to add an image from assets folder?

import img from './assets/img/myimage.png';

how can add this img to pdf?

**Comment by luizaugustoventura** [comment]
> how to add an image from assets folder?
> 
> import img from './assets/img/myimage.png';
> 
> how can add this img to pdf?

Apparently, you cannot do this. What you can do is to put the images in the android (I don't know how to do this for iOS) folder of your react native project. There is a folder called **assets** at `your_rn_project/android/app/src/main` where you can put your media files. 

To render an image in your PDF file, you are going to use something like this: `src="file:///android_asset/images/your_media_file.png"`. Note that **android_asset** points to your `your_project/android/app/src/main/assets`.

**Comment by karein** [comment]
> > how to add an image from assets folder?
> > import img from './assets/img/myimage.png';
> > how can add this img to pdf?
> 
> Apparently, you cannot do this. What you can do is to put the images in the android (I don't know how to do this for iOS) folder of your react native project. There is a folder called **assets** at `your_rn_project/android/app/src/main` where you can put your media files.
> 
> To render an image in your PDF file, you are going to use something like this: `src="file:///android_asset/images/your_media_file.png"`. Note that **android_asset** points to your `your_project/android/app/src/main/assets`.

Thank you, you gave me a north!! :)
I think it took me a few hours to get mine to work, i tried so many ways and had to generate the pdf every time..
this is how it worked for me `<img src="file:\\android_asset\\images\\img.png" />`

**Comment by bumpingChris** [comment]
I am able to get images stored in the local Documents directory to show by changing the following code in the RNHTLtoPDF.m file (lines 174-184) and writing the HTML string to a file called "html2pdf.html" saved to the Documents/htmlDirectory/ folder:
`
    NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    NSString *documentsDirectory = [paths objectAtIndex:0];
    NSURL *baseURL = [NSURL fileURLWithPath:documentsDirectory];
    NSURL *baseURL2 = [baseURL URLByAppendingPathComponent: @"htmlDirectory"];
    NSURL *baseURL3 = [baseURL2 URLByAppendingPathComponent: @"html2pdf.html"];
 
    dispatch_async(dispatch_get_main_queue(), ^{
        [_webView loadFileURL:baseURL3 allowingReadAccessToURL:baseURL];
    });
`
