### ISSUE TITLE
Can't add custom fonts on Android

### ISSUE THREAD

**Issue by marionnousvalentin** [christopherdro/react-native-html-to-pdf#95]
## Expected Behavior
When adding custom fonts in options for Android the PDF is displayed with the custom fonts.

```javascript
import Pdf from 'react-native-pdf';
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';
import RNHTMLtoPDF from 'react-native-html-to-pdf';

export class PDFReader extends React.Component<PropsType> {
  render() {
    const fontUri = resolveAssetSource(require('../../../assets/fonts/Raleway-Regular.ttf'));
    const options = {
      html: generateHTML(),
      fileName: 'test',
      directory: 'Documents',
      padding: 0,
      fonts: [fontUri && fontUri.uri],
    };
    const file = await RNHTMLtoPDF.convert(options);

    const source = { uri: `file://${file.filePath}`, cache: true };

    return (
      <Pdf
        source={source}
      />
    );
  }
}
```
```javascript
const generateHTML = () => {
return `<style type="text/css">
  @font-face { 
    font-family: ${theme.fonts.Raleway.regular};
    src: url('Raleway-Regular.ttf') format('truetype');
  }
  .block__title {
    font-family: ${theme.fonts.Raleway.regular};
  }
</style>
<span class="block__title">TITLE</span>
`
}
```
## Current Behavior
The PDF id displayed with default fonts on Android device (fonts are fine for IOS).
On other parts of my Android application, I see the custom fonts.

## Possible Solution
Maybe the commit https://github.com/christopherdro/react-native-html-to-pdf/commit/5d4092b149f25e85117c8060b1d4968f35829407 has removed this functionality.
I have looked into https://github.com/christopherdro/react-native-html-to-pdf/issues/68#issuecomment-376136830 but it didn't solve my issue.

**Comment by hannanstd** [comment]
HI
I have this problem too.
any one can help me?

**Comment by melaniebrgr** [comment]
Also having this issue. Should the README be updated to reflect that custom fonts can no longer be added via `options` at least?

**Comment by hiennguyen92** [comment]
you can custom font for Android with url as shown in the image below (with linked font files - react-native link)

![image](https://user-images.githubusercontent.com/3755347/180612288-eb8fa3c8-6f17-40ec-bab0-9c1f5c5d75ab.png)
