### ISSUE TITLE
pdf not saving on specific directory

### ISSUE THREAD

**Issue by MahbbRah** [christopherdro/react-native-html-to-pdf#96]
```js
        let options = {
            html: '<h1>This is a test PDF</h1>',
            fileName: 'test',
            directory: 'Download',
        };
```
Above is my options, Where I'm trying to save generated pdf. But it's not working and always saving to something like this: ``` /data/user/0/com.doctor_achen_patient/cache/PDF_27b08197-3da7-47e9-89f9-df9d5c1580a7-641780598.pdf```

I would like to save it on internal storage folder's like ***Download*** folder.

How could I do that?

**Comment by MahbbRah** [comment]
> ```js
>         let options = {
>             html: '<h1>This is a test PDF</h1>',
>             fileName: 'test',
>             directory: 'Download',
>         };
> ```
> 
> Above is my options, Where I'm trying to save generated pdf. But it's not working and always saving to something like this: ` /data/user/0/com.doctor_achen_patient/cache/PDF_27b08197-3da7-47e9-89f9-df9d5c1580a7-641780598.pdf`
> 
> I would like to save it on internal storage folder's like _**Download**_ folder.
> 
> How could I do that?

**Comment by DarshakShekhda** [comment]
@MahbbRah  Can you please share solution whatever you used for android ?

**Comment by MahbbRah** [comment]
> @MahbbRah Can you please share solution whatever you used for android ?

Yes, Sure

I'm using this library to do that: https://github.com/joltup/rn-fetch-blob

First, I'm generating the pdf's base64 string by this library and then simply using the ``rn-fetch-blob``` package to save it in internal/external storage

here is  a method that might help you: 
```js
createAndSavePDF = async() => {



        let options = {
            html: html_template,
            // html: '<h1>This is a test PDF</h1>',
            fileName: 'test',
            directory: 'Download',
            base64: true
        };

        let file = await RNHTMLtoPDF.convert(options)

        let filePath = RNFetchBlob.fs.dirs.DownloadDir + '/testPDF.pdf';

        // console.log(filePath);
        
        RNFetchBlob.fs.writeFile(filePath, file.base64, 'base64')
            .then(response => {
                console.log('Success Log: ', response);
            })
            .catch(errors => {
                console.log(" Error Log: ", errors);
            })


    }
```

**Comment by Ligia-Andreica** [comment]
You could use commit https://github.com/christopherdro/react-native-html-to-pdf/commit/e0e256706cfdae4824f7a98ce9f15414c4105ab1 for the Android fix. Just add this to you package.json:
```"react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf#e0e256706cfdae4824f7a98ce9f15414c4105ab1"```

**Comment by MahbbRah** [comment]
> You could use commit [e0e2567](https://github.com/christopherdro/react-native-html-to-pdf/commit/e0e256706cfdae4824f7a98ce9f15414c4105ab1) for the Android fix. Just add this to you package.json:
> `"react-native-html-to-pdf": "https://github.com/christopherdro/react-native-html-to-pdf#e0e256706cfdae4824f7a98ce9f15414c4105ab1"`

Do you understand about what we are talking?

**Comment by jjchula** [comment]
@Ligia 

Thanks. 
It works on Android.  
WRITE_EXTERNAL_STORAGE  and READ_EXTERNAL_STORAGE are also required.

**Comment by MahbbRah** [comment]
> @Ligia
> 
> Thanks.
> It works on Android.
> WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE are also required.

Yeah, You will need that definitely. I should have mentioned 👍

**Comment by harleenarora** [comment]
Hi I have android permissions, WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE both, But I have got the error: 
```
Error: Permission denied
    at Object.fn [as writeFile] (NativeModules.js:99)
    at Object.writeFile (fs.js:187)
```

I have run my app in debug mode from local system.

**Comment by Bilal-Abdeen** [comment]
Please, check my comment https://github.com/christopherdro/react-native-html-to-pdf/issues/189#issuecomment-849999309

**Comment by iamshivam0003** [comment]
I was aslo facing same issue , downgrading [react-native-html-to-pdf](https://github.com/christopherdro/react-native-html-to-pdf) to version 0.10.0 worked for me
