### ISSUE TITLE
Execution failed for task ':react-native-html-to-pdf:verifyReleaseResources'

### ISSUE THREAD

**Issue by MahbbRah** [christopherdro/react-native-html-to-pdf#98]
On Above error, I figured a solution and added a pull request. Until it's add to master branch. I'm making this as a issue to spread the problem and it's solution for awareness. 

```js
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-html-to-pdf:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```

If you find similar issue while doing release build `./gradlew assembleRelease`
https://github.com/MahbbRah/react-native-html-to-pdf

check that new commit and then you can place this command from android folder to solve this issue:
`./gradlew clean assembleRelease`

**Comment by FJiskra** [comment]
solved with:

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                buildToolsVersion "same as project version"
                compileSdkVersion same
            }
        }
    }
}

**Comment by GreenRidingHood** [comment]
https://github.com/facebook/react-native/issues/19239#issuecomment-393898039 
that solution helped me

**Comment by mirzahayat** [comment]
./gradlew clean assembleRelease
